// Polish localization file for Office
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2018/12/22 by pavroo
dict.entries['office'] = {};
// office addressbook
dict.entries['office']['abook'] = "abook jest programem książki adresowej z interfejsem tekstowym opartym na bibliotece ncurses. Zawiera wiele informacji z różnych dziedzin użytkownika. abook jest przeznaczony do użycia z mutt, ale może być używany samodzielnie.";
dict.entries['office']['dlume'] = "Dlume to prosta książka adresowa bazujaca na GTK2. Możesz łatwo dodawać, edytować i usuwać rekordy do / z bazy danych w formacie XML. Funkcja szybkiego wyszukiwania pozwala znaleźć wpis w wygodny sposób. Dostępny jest również eksport do formatu CSV i HTML. Projekt interfejsu został wypożyczony i ulepszony z Paddress.";
dict.entries['office']['kaddressbook'] = "KAddressBook pozwala na wydajne i wygodne zarządzanie kontaktami użytkownika. Może zapisywać (i wczytywać) kontakty w różnych lokalizacjach, włącznie z lokalnym systemem plików, serwerach LDAP oraz bazach danych SQL.";
dict.entries['office']['khard'] = "Khard to książka adresowa dla konsoli Linux. Tworzy, czyta, modyfikuje i usuwa wpisy z książki adresowej Carddav na komputerze lokalnym. Khard jest również kompatybilny z klientami e-mailowymi mutt i alot oraz klientem SIP Twinkle.";
dict.entries['office']['osmo'] = "Osmo to osobisty organizer, który zawiera moduły kalendarza, menedżera zadań i książki adresowej. Ma on być łatwy w użyciu i konfigurowalny, aby spełnić preferencje użytkownika.";
// office calculator
dict.entries['office']['apcalc'] = "Apcalc (oryginalna nazwa: Calc) to arbitralny system arytmetyczny, który wykorzystuje język podobny do języka C. Calc jest użyteczny jako kalkulator, prototypowy algorytm i jako narzędzie do badań matematycznych. Co ważniejsze, kalkulator dostarcza jedno z niezależnymi od maszyny środkami obliczeniowymi. Calc posiada bogaty zestaw wbudowanych funkcji matematycznych i programowych.";
dict.entries['office']['calcoo'] = "Calcoo jest kalkulatorem naukowym o zmaksymalizowanej użyteczności.";
dict.entries['office']['concalc'] = "Concalc to kalkulator dla konsoli Linux. Jest to po prostu algorytm parsera extcalc zapakowany w prosty program konsoli. Możesz go użyć, jeśli potrzebujesz kalkulatora w swojej powłoce. concalc może również uruchamiać skrypty napisane w języku programowania C.";
dict.entries['office']['galculator'] = "Galculator jest kalkulatorem naukowym. Aktualnie obsługuje różne systemy liczbowe (DEC/HEX/OCT/BIN) i jednostki miary kąta (DEG/RAD/GRAD). Program wyposażony jest w szeroką gamę matematycznych (podstawowe operacje arytmetyczne, funkcje trygonometryczne itp.) oraz innych użytecznych funkcji (pamięć itp.). Galculator może być używany w trybie algebraicznym, jak również w odwrotnej notacji polskiej (ang. Reverse Polish Notation - RPN).";
dict.entries['office']['gnomecalculator'] = "Kalkulator GNOME to potężny kalkulator graficzny z trybami finansowymi, logicznymi i naukowymi. Używa pakietu o wielu precyzjach do wykonywania arytmetyki, aby zapewnić wysoki stopień dokładności.";
dict.entries['office']['kcalc'] = "KCalc jest kalkulatorem naukowym. KCalc zapewnia: funkcje trygonometryczne, operacje logiczne i obliczenia statystyczne; obliczenia w systemie dziesiętnym, szesnastkowym, ósemkowym i dwójkowym; funkcje zapamiętywania wyników obliczeń; pełny zestaw stałych matematycznych.";
dict.entries['office']['keurocalc'] = "KEurocalc jest uniwersalnym konwerterem i kalkulatorem waluty. Pobiera najnowsze wskaźniki wymiany bezpośrednio z Europejskiego Banku Centralnego oraz Time Genie.";
dict.entries['office']['matecalc'] = "MATE-calc to potężny kalkulator graficzny z trybami finansowymi, logicznymi i naukowymi. Używa pakietu o wielu precyzjach do wykonywania arytmetyki, aby zapewnić wysoki stopień dokładności.";
dict.entries['office']['wcalc'] = "Wcalc to bardzo przydatny kalkulator. Ma standardowe funkcje (sin, asin i sinh, na przykład, w radianach lub stopniach), wiele predefiniowanych stałych (pi, e, c itd.), obsługę zmiennych, 'aktywnych' zmiennych, historia poleceń , wejście / wyjście szesnastkowe / ósemkowe / binarne, konwersje jednostek, osadzone komentarze i rozwijane pole do wprowadzania wyrażeń. Ocenia wyrażenia za pomocą standardowej kolejności operacji.";
// office document
dict.entries['office']['atril'] = "Atril jest prostą, wielostronicową przeglądarką plików zawierających dokumentację. Umożliwia wyświetlanie i drukowanie następujących formatów plików: PostScript (PS), Encapsulated PostScript (EPS), DJVU, DVI i Portable Document Format (PDF).";
dict.entries['office']['calibre'] = "Calibre stanowi kompletne rozwiązanie do e-bibliotek. Obejmuje zarządzanie bibliotekami, konwersję formatów, konwersję wiadomości do e-booków, jak również funkcje synchronizacji czytnika e-booków. Calibre jest przede wszystkim programem do katalogowania e-booków. Umożliwia użytkownikom zarządzanie kolekcją e-booków. Jest realizacją idei logicznej książki co oznacza, że został zaprojektowany tak, aby pojedynczy wpis w bazie danych mógł odnosić się do kilku formatów e-booków.";
dict.entries['office']['comix'] = "Comix jest przeglądarką komiksów. Czyta archiwa zip, rar, tar, tar.gz i tar.bz2 (często nazywane .cbz .cbr i .cbt), tak dobrze jak zwykłe pliki graficzne. Jest napisana w Pythonie i ma prosty interfejs użytkownika używającego PyGTK.";
dict.entries['office']['evince'] = "Evince jest przeglądarką dokumentów wielostronicowych. Umożliwia wyświetlanie i drukowanie plików PostScript (PS), Encapsulated PostScript (EPS), DjVu, DVI, Portable Document Format (PDF) oraz XML Paper Specification (XPS). Pozwala na wyszukiwanie tekstu, kopiowanie go do schowka, hipertekstową nawigację oraz zakładki z indeksem, gdy tylko dokument to umożliwia.";
dict.entries['office']['masterpdfeditor'] = "Master PDF Editor to prosta, łatwa w użyciu aplikacja do pracy z dokumentami PDF, wyposażona w wszechstronne funkcje. Dzięki Master PDF Editor możesz z łatwością przeglądać, tworzyć i modyfikować dokumenty PDF. Aplikacja umożliwia scalanie wielu plików w jeden, dzielenie dokumentu źródłowego na wiele dokumentów, a także komentowanie, podpisywanie i szyfrowanie plików PDF.";
dict.entries['office']['mcomix'] = "MComix jest przyjazną dla użytkownika przeglądarką obrazów. Została specjalnie zaprojektowana do obsługi komiksów, ale służy również jako przeglądarka ogólnego zastosowania. Odczytuje obrazy w archiwach ZIP, RAR, 7Zip lub tar, a także zwykłych plików graficznych. Jest napisany w języku Python i używa GTK+ przez powiązania PyGTK i działa zarówno na Linuksie, jak i na Windowsie.";
dict.entries['office']['mupdf'] = "MuPDF to lekka przeglądarka plików PDF i zestaw narzędzi napisany w języku C. Odczytuje również dokumenty XPS, OpenXPS i ePub. Renderowanie w MuPDF jest dostosowane do wysokiej jakości antyaliasingu grafiki. Reprezentuje tekst z metrykami i odstępami z dokładnością do ułamków piksela, zapewniając najwyższą wierność odwzorowania wyglądu wydrukowanej strony na ekranie.";
dict.entries['office']['okular'] = "Okular jest uniwersalnym programem do przeglądania dokumentów, umożliwiającym obsługę zaawansowanych funkcji takich jak: adnotacje, formularze i osadzone pliki. Pakiet zawiera przeglądarkę dokumentów oraz wtyczki do wielu różnych formatów dokumentów.";
dict.entries['office']['qpdfview'] = "Qpdfview to prosta przeglądarka dokumentów z zakładkami, która wykorzystuje bibliotekę Poppler do renderowania PDF i CUPS do drukowania oraz zapewnia przejrzysty i prosty graficzny interfejs użytkownika Qt. Obsługa formatów DjVu i PostScript może być dodana za pomocą wtyczek.";
dict.entries['office']['xpdf'] = "Program xpdf jest lekką, otwartoźródłową przeglądarką plików PDF (ang. Portable Document Format), zwanych również plikami Adobe Acrobat lub Acrobat. Pakiet zawiera samą przeglądarkę; różne narzędzia wiersza poleceń związane z plikami PDF znajdują się w pakiecie poppler-utils.";
// office note
dict.entries['office']['feathernotes'] = "FeatherNotes to lekki hierarchiczny menedżer notatek Qt5 dla systemu Linux. Jest niezależny od środowiska graficznego.";
dict.entries['office']['gnote'] = "Gnote to prosta i łatwa w użytkowaniu aplikacja do tworzenia notatek na pulpicie. Pozwala użytkownikowi na organizowanie notatek w zmyślny sposób, poprzez umożliwienie mu łączenia pomysłów na wzór odnośników w stylu Wiki.";
dict.entries['office']['keepnote'] = "Dzięki KeepNote możesz przechowywać notatki, listy zadań, notatki z badań, wpisy do dziennika, zarysy, itp. w prostej hierarchii notebooków z formatowaniem tekstu sformatowanego, obrazami i wieloma innymi elementami. Korzystając z wyszukiwania pełnotekstowego, możesz pobrać dowolną notatkę do późniejszego wykorzystania. KeepNote ma być wieloplatformowy (zaimplementowany w Pythonie i PyGTK), przechowuje notatki w prostych i łatwych do manipulowania formatach plików (HTML i XML). Archiwizowanie i przenoszenie notatek jest tak proste jak skompresowanie lub skopiowanie folderu.";
dict.entries['office']['kjots'] = "Kjots jest programem do sporządzania notatek, organizującym je w grupy stron. Pakiet jest częścią modułu PIM KDE.";
dict.entries['office']['knotes'] = "KNotes to program, który umożliwia tworzenie notatek na samoprzylepnych karteczkach. Notatki są automatycznie zapisywane przy zamknięciu programu i wyświetlane po jego uruchomieniu. Program umożliwia drukowanie i rozsyłanie notatek.";
dict.entries['office']['noblenote'] = "nobleNote to program do porządkowania i tworzenia notatek. Ma ikonę w zasobniku systemowym i obsługuje przeciąganie i upuszczanie. Edytor notatek obsługuje różne czcionki, rozmiary i kolory czcionek oraz kolory tła. Możesz także importować notatki z innych programów, takich jak gnote i tomboy. Notatki są zapisywane w formacie html.";
dict.entries['office']['note'] = "Jest to mały program konsolowy podobny do programu knotes, który pozwala na zarządzanie notatkami z linii poleceń. Note może wykorzystywać różne bazy danych do przechowywania notatek. Jest dostarczany z modułem mysql opartym na DBI (który może być również używany przez inne osoby za pośrednictwem DBMS) i innym modułem, który wykorzystuje plik binarny do przechowywania i moduł DBM.";
dict.entries['office']['rhinote'] = "Rhinote to niewielki program dostarczający wirtualne notatki. Przydaje się do zapisywania szybkich notatek lub kopiowania tekstu, który planujesz wkleić później. Notatki mogą być zapisane jako zwykły tekst do późniejszego przeglądania / edycji za pomocą Rhinote lub dowolnego innego edytora tekstu. Rhinote ma być 'przyjazny dla klawiatury', to znaczy każda akcja jest przypisana do określonego klawisza.";
dict.entries['office']['tomboy'] = "Tomboy jest łatwą w użyciu aplikacją do tworzenia notatek na pulpicie. Umożliwia Ci organizowanie notatek w inteligentny sposób dzięki łatwemu łączeniu ich odnośnikami w stylu Wiki.";
dict.entries['office']['xfce4notes'] = "Aplikacja notesu dla pulpitu Xfce4. Narzędzie notes dostarcza prosty edytor tekstu w niewielkim oknie pulpitu Xfce4. Jest przydatny szczególnie przy chwilowych zajęciach. Obsługuje wiele notatek w notatniku. Kliknięcie przycisku w górnym lewym rogu otwiera nową notatkę.";
// office others
dict.entries['office']['calcurse'] = "CalCurse to konsolowy kalendarz i menadżer zadań, który pozwala na śledzenie terminów i codziennych zadań. CalCurse ma ładny interfejs trybu tekstowego z konfigurowalnymi schematami kolorów, konfigurowalnym układem i klawiszami podobnymi do Vi.";
dict.entries['office']['gcalcli'] = "gcalcli to aplikacja Pythona, która umożliwia dostęp do Kalendarza Google z poziomu wiersza poleceń. Łatwo jest wyszukać wydarzenia i szybko dodać nowe. Dodatkowo gcalcli może być używany jako usługa przypomnienia do wykonania dowolnej aplikacji.";
dict.entries['office']['jpilot'] = "J-Pilot to aplikacja organizera pulpitu do urządzeń z systemem PalmOS. Jest alternatywą do środowiska Palm dostarczanego przez Palm.";
dict.entries['office']['scribus'] = "Scribus jest otwartoźródłowym programem komputerowym do składania stron, mającym na celu tworzenie dobrych jakościowo plików wyjściowych w formacie PDF i Postscript. Scribus może być stosowany do wielu zadań; do projektowania broszur, gazet, czasopism, biuletynów, plakatów oraz dokumentacji technicznej.";
dict.entries['office']['simplescan'] = "Simple Scan to prosta w użyciu aplikacja zaprojektowana tak, by umożliwić użytkownikom podłączenie skanera i w krótkim czasie otrzymać obraz/dokument w odpowiednim formacie.";
dict.entries['office']['systemconfigprinter'] = "System-config-printer jest graficznym interfejsem napisanym w Pythonie przy użyciu GTK+, do konfigurowania serwera CUPS. Jego głównym zadaniem jest konfiguracja systemu druku na lokalnym komputerze, ale może być także użyty do ustawiania drukarki zdalnej. Pod względem funkcji, ma być tak kompletny jak webowe narzędzie administracyjne CUPS, będąc jednocześnie zintegrowanym ze środowiskiem graficznym.";
dict.entries['office']['xsane'] = "Wielofunkcyjna graficzna nakładka na SANE (Scanner Access Now Easy). xsane może być uruchamiany jako samodzielny program lub poprzez GIMP-a (GNU Image Manipulation Program). W trybie samodzielnym xsane może zapisywać obrazy do plików w różnych formatach, służyć jako nakładka do programu faksującego lub wysłać obrazki na drukarkę.";
// office spreadsheet
dict.entries['office']['calligrasheets'] = "Arkusz kalkulacyjny do Calligra Suite. Obsługuje skrypty i zapewnia zarówno arkusze zorientowane na tabele, jak i wsparcie dla złożonych formuł matematycznych i statystycznych. Jest następcą KSpread.";
dict.entries['office']['gnumeric'] = "Gnumeric jest arkuszem kalkulacyjnym dobrze współpracującym z innymi programami tego typu. Jest wyposażony we wtyczki umożliwiające współpracę z najpowszechniej używanymi formatami plików arkusza kalkulacyjnego.";
dict.entries['office']['pyspread'] = "Pyspread to wieloplatformowa aplikacja do obsługi arkuszy kalkulacyjnycj, bazująca na Pythonie. Zamiast formuł arkusza kalkulacyjnego, wyrazy w języku Python są wprowadzane do komórek arkusza kalkulacyjnego. Każde wyrażenie zwraca obiekt Pythona, do którego można uzyskać dostęp z innych komórek. Obiekty te mogą reprezentować wszystko, w tym listy lub macierze.";
dict.entries['office']['scoffice'] = "SC (Spreadsheet Calculator) jest zmodyfikowaną wersją sc dostępnego w domenie publicznej, który kilka lat temu został opublikowany w serwisie Usenet przez Marka Weisera jako vc, pierwotnie autorstwa Jamesa Goslinga. Opiera się na tabelach, podobnie jak arkusz kalkulacyjny. Jego klawisze są znane użytkownikom 'vi' a większość funkcji ma czysty arkusz kalkulacyjny, ale brakuje w nim grafów i zapisów w obcych formatach. Jest bardzo stabilny i całkiem łatwy w użyciu, gdy już trochę się nauczysz.";
// office suite
dict.entries['office']['calligra'] = "Calligra Suite to zestaw aplikacji napisanych, aby pomóc Ci wykonać pracę. Obejmuje aplikacje biurowe, takie jak procesor tekstu, arkusz kalkulacyjny, program prezentacji, aplikację bazy danych itp. oraz narzędzia grafiki rastrowej i wektorowej.";
dict.entries['office']['libreoffice'] = "LibreOffice to w pełni funkcjonalny pakiet biurowy, który zapewnia zastępstwo dla pakietu Microsoft (R) Office. Spowoduje to zainstalowanie wszystkich komponentów: edytora tekstu, arkusza kalkulacyjnego, prezentacji, rysunku, bazy danych, edytora równań.";
dict.entries['office']['msonlineapps'] = "Instaluje skróty Menu dla aplikacji internetowych firmy Microsoft.";
dict.entries['office']['onlyoffice'] = "ONLYOFFICE DesktopEditors to aplikacja do edytowania dokumentów biurowych (dokumentów tekstowych, arkuszy kalkulacyjnych i prezentacji) na komputerze lokalnym bez użycia przeglądarki, od portalu biurowego ONLYOFFICE.";
dict.entries['office']['openoffice'] = "Apache OpenOffice to pakiet oprogramowania biurowego typu open-source do przetwarzania tekstów, arkuszy kalkulacyjnych, prezentacji, grafiki, baz danych i innych. Jest dostępny w wielu językach i działa na wszystkich typowych komputerach.";
dict.entries['office']['wpsoffice'] = "WPS Office (dawniej znany jako Kingsoft Office) to pakiet biurowy. Charakteryzuje go szybkość działania oraz fakt, że jest dostępny za darmo. W skład pakietu wchodzą aplikacje: Presentation będąca narzędziem do tworzenia prezentacji multimedialnych, Writer edytor tekstu oraz arkusz kalkulacyjny Spreadsheets.";
// office text
dict.entries['office']['abiword'] = "AbiWord jest w pełni funkcjonalnym, wydajnym procesorem tekstu. Jest przydatny w wielu zastosowaniach związanych z przetwarzaniem tekstu, a dzięki różnym wtyczkom można rozszerzyć jego możliwości. Pakiet zawiera wiele z dostępnych wtyczek importu/eksportu umożliwiających programowi AbiWord obsługę formatów ODT, WordPerfect i wielu innych. Zawiera wtyczki umożliwiające współpracę w czasie rzeczywistym użytkowników AbiWorda na Linuksie i Windowsie (używając TCP lub Jabber/XMPP), tłumaczenie przez WWW, obsługę słowników i wiele innych funkcji.";
dict.entries['office']['bluefish'] = "Bluefish to rozbudowany edytor przeznaczony dla programistów oraz web deweloperów. Posiada wiele opcji przydatnych podczas tworzenia stron internetowych, pisania skryptów oraz programowania. Obsługuje szeroką gamę języków programowania oraz języków znaczników.";
dict.entries['office']['bluegriffon'] = "BlueGriffon to edytor treści typu WYSIWYG dla stron World Wide Web. Obsługiwany przez Gecko, silnik renderujący Firefoksa, jest nowoczesnym i niezawodnym rozwiązaniem do edycji stron internetowych zgodnie z najnowszymi standardami sieci.";
dict.entries['office']['emacs'] = "GNU Emacs jest rozszerzalnym samodokumentującym się edytorem tekstu. To metapakiet, który zawsze będzie zależeć od najnowszego zalecanego wariantu Emacsa (obecnie emacs-gtk).";
dict.entries['office']['featherpad'] = "FeatherPad to lekki edytor tekstu Qt5 dla systemu Linux. Jest niezależny od środowiska graficznego i posiada wszystkie funkcje, których można się spodziewać w nowoczesnym edytorze.";
dict.entries['office']['geany'] = "Geany jest małym i lekkim zintegrowanym środowiskiem developerskim. Został zaprojektowany w celu dostarczenia małego i szybkiego IDE, wymagającego do działania jedynie kilku innych pakietów. Używa wyłącznie zestawu narzędzi GTK2, w związku z czym do jego uruchomienia wymagane są tylko biblioteki uruchomieniowe GTK2.";
dict.entries['office']['gedit'] = "Gedit jest edytorem tekstu obsługującym większość typowych funkcji edytora, rozszerzając podstawowe możliwości o inne, rzadsze funkcje, których nie można znaleźć w zwykłych edytorach. Gedit jest graficzną aplikacją obsługującą edytowanie wielu plików w jednym oknie (funkcja nazywana czasami kartami albo MDI).";
dict.entries['office']['kate'] = "Kate jest funkcjonalnym edytorem tekstu, umożliwiającym otwieranie wielu plików jednocześnie. Z wbudowanym terminalem, podświetlaniem składni oraz paskiem bocznym z kartami, sprawdza się jako lekkie ale nadające się do rozwoju środowisko. Wiele narzędzi, wtyczek i skryptów sprawia, że Kate jest wysoce konfigurowalnym programem.";
dict.entries['office']['kwrite'] = "KWrite jest prostym edytorem tekstu wbudowanym w KDE Platform. Używa komponentu edytora Kate, obsługuje więc zaawansowane funkcje, takie jak: elastyczne podkreślanie składni, automatyczne wcięcia oraz wiele innych narzędzi tekstowych.";
dict.entries['office']['leafpad'] = "Leafpad jest prostym edytorem tekstu bazującym na GTK+ o interfejsie użytkownika podobnym jak w Notatniku. Ma na celu bycie lżejszym niż GEdit i KWrite, ale tak samo użytecznym.";
dict.entries['office']['leo'] = "Leo to PIM, IDE i edytor napisany w 100% czystym Pythonie. Leo zawiera edytor konturów z wieloma oknami, kolorowanie Pythona, zaawansowane polecenia konspektu i wiele innych rzeczy, w tym nieograniczone cofanie / ponawianie i zintegrowane okno powłoki Pythona (IDLE).";
dict.entries['office']['mousepad'] = "Mousepad jest graficznym edytorem tekstu dla Xfce bazującym na Leafpad. Głównym powodem powstania Mousepad było dostarczenie wsparcia dla drukarek, co z wielu powodów byłoby trudne w Leafpad.";
dict.entries['office']['nano'] = "GNU nano jest łatwym w użyciu edytorem tekstu, początkowo zaprojektowanym jako zamiennik Pico, edytora poczty bazującego na ncurses z odpłatnego pakietu Pine (teraz dostępny samodzielnie w ramach Apache License jako Alpine).";
dict.entries['office']['notepadqq'] = "Edytor tekstu podobny do Notepad++ dla systemu Linux z obsługą wielu języków programowania, wieloma kodowaniami i obsługą wtyczek.";
dict.entries['office']['pluma'] = "Pluma jest edytorem tekstu obsługującym większość typowych funkcji edytora, rozszerzając podstawowe możliwości o inne, rzadsze funkcje, których nie można znaleźć w zwykłych edytorach. Pluma jest graficzną aplikacją obsługującą edytowanie wielu plików w jednym oknie (funkcja nazywana czasami kartami albo MDI).";
dict.entries['office']['vim'] = "Vi IMproved - udoskonalony edytor vi. Vim jest prawie całkowicie kompatybilny z edytorem Vi pochodzącym z UNIX-a. Dodano wiele nowych funkcji: wielopoziomowe cofanie, podświetlanie składni, historię wydawanych poleceń, podręczną pomoc, uzupełnianie nazw plików, operacje blokowe, zwijanie (folding), wsparcie dla Unicode itd.";
