// English localization file for Office
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2020/01/01 by pavroo
dict.entries['office'] = {};
// office addressbook
dict.entries['office']['abook'] = "abook is a text-based ncurses address book application. It provides many different fields of user info. abook is designed for use with mutt, but can be used independently.";
dict.entries['office']['dlume'] = "Dlume is a simple, gtk2-based addressbook. You can easily add, edit and delete records to/from an XML-format database. The Quick-search feature allows you find required entry in comfortable way. Export to CSV and HTML formats is also available. Interface design was borrowed and improved from Paddress.";
dict.entries['office']['kaddressbook'] = "KAddressBook enables you to manage your contacts efficiently and comfortably. It can load and save your contacts to many different locations, including the local file system, LDAP servers, and SQL databases.";
dict.entries['office']['khard'] = "Khard is an address book for the Linux console. It creates, reads, modifies and removes carddav address book entries at your local machine. Khard is also compatible to the email clients mutt and alot and the SIP client Twinkle.";
dict.entries['office']['osmo'] = "Osmo is a personal organizer, which includes calendar, task manager and address book modules. It aims to be easy to use and configurable to meet the user's preferences.";
// office calculator
dict.entries['office']['apcalc'] = "Apcalc (original name: Calc) is an arbitrary precision arithmetic system that uses a C-like language. Calc is useful as a calculator, an algorithm prototyper and as a mathematical research tool. More importantly, calc provides one with a machine independent means of computation. Calc comes with a rich set of builtin mathematical and programmatic functions.";
dict.entries['office']['calcoo'] = "Calcoo is a scientific calculator designed to provide maximum usability.";
dict.entries['office']['concalc'] = "Concalc is a calculator for the Linux console. It is just the parser-algorithm of extcalc packed into a simple console program. You can use it if you need a calculator in your shell. concalc is also able to run scripts written in a C-like programming language.";
dict.entries['office']['qalculategtk'] = "Qalculate! is small and simple to use but with much power and versatility underneath. Features include customizable functions, units, arbitrary precision, plotting, and a graphical interface that uses a one-line fault-tolerant expression entry.";
dict.entries['office']['galculator'] = "Galculator is a scientific calculator. It supports different number bases (DEC/HEX/OCT/BIN) and angles bases (DEG/RAD/GRAD) and features a wide range of mathematical (basic arithmetic operations, trigonometric functions, etc) and other useful functions (memory, etc) at the moment. galculator can be used in algebraic mode as well as in Reverse Polish Notation (RPN).";
dict.entries['office']['gnomecalculator'] = "The GNOME calculator is a powerful graphical calculator with financial, logical and scientific modes. It uses a multiple precision package to do its arithmetic to give a high degree of accuracy.";
dict.entries['office']['kcalc'] = "KCalc is a scientific calculator. KCalc provides: Trigonometric functions, logic operations, and statistical calculations; Calculation in decimal, hexadecimal, octal, and binary bases; Memory functions for storing results; A comprehensive collection of mathematical constants.";
dict.entries['office']['keurocalc'] = "KEurocalc is a universal currency converter and calculator. It downloads latest exchange rates directly from the European Central Bank and Time Genie.";
dict.entries['office']['matecalc'] = "MATE-calc is a powerful graphical calculator with financial, logical and scientific modes. It uses a multiple precision package to do its arithmetic to give a high degree of accuracy.";
dict.entries['office']['qcalculator'] = "Simply and small Qt based Calculator.";
dict.entries['office']['wcalc'] = "Wcalc is a very capable calculator. It has standard functions (sin, asin, and sinh for example, in either radians or degrees), many pre-defined constants (pi, e, c, etc.), support for using variables, 'active' variables, a command history, hex/octal/binary input and output, unit conversions, embedded comments, and an expandable expression entry field. It evaluates expressions using the standard order of operations.";
// office document
dict.entries['office']['atril'] = "Atril is a simple multi-page document viewer. It can display and print PostScript (PS), Encapsulated PostScript (EPS), DJVU, DVI and Portable Document Format (PDF) files.";
dict.entries['office']['calibre'] = "Calibre is a complete e-library solution. It includes library management, format conversion, news feeds to e-book conversion, e-book viewer and editor, and e-book reader sync features. Calibre is primarily an e-book cataloging program. It manages your e-book collection for you. It is designed around the concept of the logical book, i.e. a single entry in the database that may correspond to e-books in several formats. It also supports conversion to and from a dozen different e-book formats.";
dict.entries['office']['comix'] = "Comix is a comic book viewer. It reads zip, rar, tar, tar.gz and tar.bz2 archives (often called .cbz, .cbr and .cbt) as well as normal image files. It is written in Python and has a simple user interface using PyGTK.";
dict.entries['office']['evince'] = "Evince is a simple multi-page document viewer. It can display and print PostScript (PS), Encapsulated PostScript (EPS), DjVu, DVI, Portable Document Format (PDF) and XML Paper Specification (XPS) files. When supported by the document, it also allows searching for text, copying text to the clipboard, hypertext navigation, and table-of-contents bookmarks.";
dict.entries['office']['masterpdfeditor'] = "Master PDF Editor is straightforward, easy to use application for working with PDF documents equipped with powerful multi-purpose functionality. With Master PDF Editor you can easily view, create and modify PDF documents. The application enables you to merge several files into one, split a source document into multiple documents, and also to comment, sign and encrypt PDF files.";
dict.entries['office']['mcomix'] = "MComix is an user-friendly, customizable image viewer. It is specifically designed to handle comic books, but also serves as a generic viewer. It reads images in ZIP, RAR, 7Zip or tar archives as well as plain image files. It is written in Python and uses GTK+ through the PyGTK bindings, and runs on both Linux and Windows.";
dict.entries['office']['mupdf'] = "MuPDF is a lightweight PDF viewer and toolkit written in portable C. It also reads XPS, OpenXPS and ePub documents. The renderer in MuPDF is tailored for high quality anti-aliased graphics. It renders text with metrics and spacing accurate to within fractions of a pixel for the highest fidelity in reproducing the look of a printed page on screen.";
dict.entries['office']['okular'] = "Okular is a universal document viewer with support for advanced document features, such as annotations, forms, and embedded files. This package provides the document viewer application, plus plugins for a wide variety of document formats.";
dict.entries['office']['qpdfview'] = "Qpdfview is a simple tabbed document viewer which uses the Poppler library for PDF rendering and CUPS for printing and provides a clear and simple Qt graphical user interface. Support for the DjVu and PostScript formats can be added via plugins.";
dict.entries['office']['xpdf'] = "xpdf is a light-weight open source viewer for Portable Document Format (PDF) files (also called 'Adobe Acrobat' or 'Acrobat' files). This is just the xpdf viewer client; various command-line pdf tools are now provided via the poppler-utils package.";
// office note
dict.entries['office']['feathernotes'] = "FeatherNotes is a lightweight Qt5 hierarchical notes-manager for Linux. It is independent of any desktop environment.";
dict.entries['office']['gnote'] = "Gnote is a desktop note-taking application which is simple and easy to use. It lets you organise your notes intelligently by allowing you to easily link ideas together with Wiki style interconnects.";
dict.entries['office']['keepnote'] = "With KeepNote, you can store your class notes, TODO lists, research notes, journal entries, paper outlines, etc in a simple notebook hierarchy with rich-text formatting, images, and more. Using full-text search, you can retrieve any note for later reference. KeepNote is designed to be cross-platform (implemented in Python and PyGTK) and stores your notes in simple and easy to manipulate file formats (HTML and XML). Archiving and transferring your notes is as easy as zipping or copying a folder.";
dict.entries['office']['kjots'] = "Kjots is a notebook utility that organizes notes using groups of pages. This package is part of the KDE PIM module.";
dict.entries['office']['knotes'] = "KNotes is a program that lets you write sticky notes. The notes are saved automatically when you exit the program, and they display when you open the program. The program supports printing and mailing your notes.";
dict.entries['office']['noblenote'] = "nobleNote is a program to organize and create notes. It has an icon in the system tray and supports drag and drop. The note-editor supports different fonts, font sizes and colors as well as background colors. You can also import notes from other programs like gnote and tomboy. The notes are saved in the html format.";
dict.entries['office']['note'] = "This is a small console program similar to knotes, which allows you to manage notes from commandline. Note can use different database-backends for notes-storage. It ships with a DBI-based mysql-module (which can also be used by others through a DBI-based supported DBMS) and another module, which uses a binary file for storage and a DBM module.";
dict.entries['office']['rhinote'] = "Rhinote is a small program that provides virtual sticky-notes. It's handy for jotting down quick notes or holding copied text that you plan to paste elsewhere later. Notes can be saved as plain text for later viewing/editing with Rhinote or any other text editor. Rhinote is designed to be 'keyboard friendly', that is, every single action is bound to a specific keystroke.";
dict.entries['office']['tomboy'] = "Tomboy is a desktop note-taking application which is simple and easy to use. It lets you organise your notes intelligently by allowing you to easily link ideas together with Wiki style interconnects.";
dict.entries['office']['xfce4notes'] = "Notes application for the Xfce4 desktop. The notes tool provides you a simple text editor in a little window for the Xfce 4 desktop. Notes are especially useful for temporary stuff. It supports multiple notes through a notebook. Click on the upper left corner button to open a new note.";
// office others
dict.entries['office']['calcurse'] = "CalCurse is a calendar and todo list for the console which allows you to keep track of your appointments and everyday tasks. CalCurse has a nice textmode interface with configurable color schemes, configurable layout and Vi-like keybindings.";
dict.entries['office']['gcalcli'] = "gcalcli is a Python application that allows you to access your Google Calendar from a command line. It's easy to get your agenda, search for events, and quickly add new events. Additionally gcalcli can be used as a reminder service to execute any application you want.";
dict.entries['office']['jpilot'] = "J-Pilot is a desktop organizer application for PalmOS devices. It is meant to be an alternative to the Palm Desktop provided by Palm.";
dict.entries['office']['scribus'] = "Scribus is an open source desktop page layout program with the aim of producing commercial grade output in PDF and Postscript. Scribus can be used for many tasks; from brochure design to newspapers, magazines, newsletters and posters to technical documentation.";
dict.entries['office']['simplescan'] = "Simple Scan is an easy-to-use application, designed to let users connect their scanner and quickly have the image/document in an appropriate format.";
dict.entries['office']['systemconfigprinter'] = "System-config-printer is a GUI written in Python using GTK+ to configure a CUPS server. Its primary use is to configure the printing system on the local host, but can also be used to setup a remote printer. In terms of features, it aims to be as complete as the CUPS web administration tool, while being integrated to the desktop.";
dict.entries['office']['xsane'] = "Featureful graphical frontend for SANE (Scanner Access Now Easy). xsane can be run as a stand-alone program or through the GIMP image manipulation program. In stand-alone mode, xsane can save an image to a file in a variety of image formats, serve as a frontend to a fax program, or send an image to a printer.";
// office spreadsheet
dict.entries['office']['calligrasheets'] = "Spreadsheet for the Calligra Suite. It is scriptable and provides both table-oriented sheets and support for complex mathematical formulae and statistics. It is the successor of KSpread.";
dict.entries['office']['gnumeric'] = "Gnumeric is a spreadsheet application that interoperates well with other spreadsheets. It comes with plugins that enable it to deal with commonly used spreadsheet file formats.";
dict.entries['office']['pyspread'] = "Pyspread is a cross-platform Python spreadsheet application. Instead of spreadsheet formulas, Python expressions are entered into the spreadsheet cells. Each expression returns a Python object that can be accessed from other cells. These objects can represent anything including lists or matrices.";
dict.entries['office']['scoffice'] = "Spreadsheet Calculator is a much modified version of the public- domain spread sheet sc, which was posted to Usenet several years ago by Mark Weiser as vc, originally by James Gosling. It is based on rectangular table much like a financial spreadsheet. Its keybindings are familiar to users of 'vi', and it has most features that a pure spreadsheet would, but lacks things like graphing and saving in foreign formats. It's very stable and quite easy to use once you've put a little effort into learning it.";
// office suite
dict.entries['office']['calligra'] = "Calligra Suite is a set of applications written to help you to accomplish your work. It includes office applications such as a word processor, a spreadsheet, a presentation program, a database application, etc., and raster and vector graphics tools.";
dict.entries['office']['freeoffice'] = "FreeOffice is a complete Office suite with a word processor, a spreadsheet application and a presentation program – all compatible with their counterparts in Microsoft Office.";
dict.entries['office']['libreoffice'] = "LibreOffice is a full-featured office productivity suite that provides a near drop-in replacement for Microsoft(R) Office. This installs all components of: Word processor, Spreadsheet, Presentation, Drawing, Database, Equation editor.";
dict.entries['office']['msonlineapps'] = "It installs Menu shorcuts for Microsoft Online Applications.";
dict.entries['office']['onlyoffice'] = "ONLYOFFICE DesktopEditors is an application for editing office documents (text documents, spreadsheets and presentations) from ONLYOFFICE cloud portal on local computer without browser using.";
dict.entries['office']['openoffice'] = "Apache OpenOffice is the open-source office software suite for word processing, spreadsheets, presentations, graphics, databases and more. It is available in many languages and works on all common computers.";
dict.entries['office']['wpsoffice'] = "WPS Office (formerly known as Kingsoft Office) is an office suite. It is characterized by the speed of action and the fact that it is available for free. The package includes the following applications: Presentation which is a tool for creating multimedia presentations, Writer text editor and spreadsheets spreadsheet.";
// office text
dict.entries['office']['abiword'] = "AbiWord is a full-featured, efficient word processing application. It is suitable for a wide variety of word processing tasks, and is extensible with a variety of plugins. This package includes many of the available import/export plugins allowing AbiWord to interact with ODT, WordPerfect, and other formats. It also includes tools plugins, offering live collaboration with AbiWord users on Linux and Windows (using TCP or Jabber/XMPP), web translation and dictionary support, and more.";
dict.entries['office']['atom'] = "A text editor of programming source codes with syntax highlighting for many languages. You can also edit all txt files as well.";
dict.entries['office']['bluefish'] = "Bluefish is a powerful editor targeted towards programmers and web developers, with many options to write websites, scripts and programming code. Bluefish supports a wide variety of programming and markup languages and has many features.";
dict.entries['office']['bluegriffon'] = "BlueGriffon is a WYSIWYG content editor for the World Wide Web. Powered by Gecko, the rendering engine of Firefox, it's a modern and robust solution to edit Web pages in conformance to the latest Web Standards.";
dict.entries['office']['emacs'] = "GNU Emacs is the extensible self-documenting text editor. This is a metapackage that will always depend on the latest recommended Emacs variant (currently emacs-gtk).";
dict.entries['office']['featherpad'] = "FeatherPad is a lightweight Qt5 plain-text editor for Linux. It is independent of any desktop environment and comes with all features one would expect in a modern editor.";
dict.entries['office']['geany'] = "Geany is a small and lightweight integrated development environment. It was developed to provide a small and fast IDE, which has only a few dependencies from other packages. It is using only the GTK2 toolkit and therefore you need only the GTK2 runtime libraries to run Geany.";
dict.entries['office']['gedit'] = "Gedit is a text editor which supports most standard editor features, extending this basic functionality with other features not usually found in simple text editors. gedit is a graphical application which supports editing multiple text files in one window (known sometimes as tabs or MDI).";
dict.entries['office']['kate'] = "Kate is a powerful text editor that can open multiple files simultaneously. With a built-in terminal, syntax highlighting, and tabbed sidebar, it performs as a lightweight but capable development environment. Kate's many tools, plugins, and scripts make it highly customizable.";
dict.entries['office']['kwrite'] = "KWrite is a simple text editor built on the KDE Platform. It uses the Kate editor component, so it supports powerful features such as flexible syntax highlighting, automatic indentation, and numerous other text tools.";
dict.entries['office']['leafpad'] = "Leafpad is a simple GTK+ based text editor, the user interface is similar to Notepad. It aims to be lighter than GEdit and KWrite, and to be as useful as them.";
dict.entries['office']['leo'] = "Leo is a PIM, IDE and outliner written in 100% pure Python. Leo features a multi-window outlining editor, Python colorizing, powerful outline commands and many other things, including unlimited Undo/Redo and an integrated Python shell(IDLE) window.";
dict.entries['office']['mousepad'] = "Mousepad is a graphical text editor for Xfce based on Leafpad. The initial reason for Mousepad was to provide printing support, which would have been difficult for Leafpad for various reasons.";
dict.entries['office']['nano'] = "GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).";
dict.entries['office']['notepadqq'] = "Notepad++-like editor for Linux with support for multiple programming languages, multiple encodings and plugin support.";
dict.entries['office']['pluma'] = "Pluma is a text editor which supports most standard editor features, extending this basic functionality with other features not usually found in simple text editors. Pluma is a graphical application which supports editing multiple text files in one window (known sometimes as tabs or MDI).";
dict.entries['office']['vim'] = "Vi IMproved - enhanced vi editor. Vim is an almost compatible version of the UNIX editor Vi. Many new features have been added: multi level undo, syntax highlighting, command line history, on-line help, filename completion, block operations, folding, Unicode support, etc.";
