// English localization file for Multimedia
// Originally created by Piotr "MoroS" Mrożek 2018
// Under the GNU GPL v3
// Last update 2018/12/10 by pavroo
dict.entries['media'] = {};
// multimedia audio players
dict.entries['media']['alsaplayergui'] = "alsaplayer GTK interface";
dict.entries['media']['amarok'] = "Amarok is a powerful music player with an intuitive interface. It makes playing the music you love and discovering new music easier than ever before and it looks good doing it! Amarok is based on the powerful Qt4 / KDE4 Platform and nicely integrates with KDE desktop.";
dict.entries['media']['audacious'] = "Small and fast audio player which supports lots of formats. Audacious is a fork of beep-media-player which supports Winamp skins and many codecs.";
dict.entries['media']['cantata'] = "Cantata is a graphical front-end for the music player daemon, MPD. It provides many tools to view and manage the music collection.";
dict.entries['media']['clementine'] = "Clementine is a multiplatform music player focusing on a fast and easy-to-use interface for searching and playing your music.";
dict.entries['media']['cmus'] = "C* Music Player is a modular and very configurable ncurses-based audio player. It has some interesting features like configurable colorscheme, mp3 and ogg streaming, it can be controlled with an UNIX socket, filters, album/artists sorting and a vi-like configuration interface.";
dict.entries['media']['deadbeef'] = "DeaDBeeF is an audio player for GNU/Linux, *BSD, OpenSolaris, Mac OS X, and other UNIX-like systems.";
dict.entries['media']['dradio'] = "Dradio is a terminal based frontend to MPlayer that collects the available channels/podcasts for convenient browsing.";
dict.entries['media']['exaile'] = "Exaile is a media player which incorporates many of the cool things from Amarok (and other media players) like automatic fetching of album art, handling of large libraries, lyrics fetching, artist/album information via Wikipedia, last.fm support, and optional iPod support.";
dict.entries['media']['gmerlin'] = "Gmerlin is a multiformat media player with tree-like virtual directory structure, where you can save your files, webstreams or whatever. It handles even large media collections gracefully. Hardware devices appear also in the tree so you can open Audio-CDs, (S)VCDs, DVDs and DVB-broadcasts.";
dict.entries['media']['gmusicbrowser'] = "gmusicbrowser is a powerful graphical browser which supports libraries with a very large number of songs (over 10,000). It can use multiple inputs and has native support for MP3, Ogg, and FLAC files. It also supports mass-renaming and mass-retagging of a song library, multiple genres per song, ratings, and customizable labels.";
dict.entries['media']['gnomemusic'] = "Music is the new GNOME music playing application aiming at being a simple and elegant replacement for using Files to show the Music directory. Objectives includes listening to local and online/cloud collections, listen to music on attached devices, listen to music shared by friends, listen to audiobooks, a player for DLNA media servers, share music, upload music and select favorites.";
dict.entries['media']['gradio'] = "A GTK3 app for finding and listening to internet radio stations.";
dict.entries['media']['jajuk'] = "Jajuk is software that organizes and plays music. Jajuk is designed to be intuitive, fast and provide multiple ways to perform the same operation. It is a fully-featured application geared towards advanced users with very large or scattered music collections.";
dict.entries['media']['juk'] = "JuK is a free software audio player by KDE, the default player since K Desktop Environment 3.2. JuK supports collections of MP3, Ogg Vorbis, and FLAC audio files.";
dict.entries['media']['kscd'] = "KsCD is an audio CD player. It uses the Compact Disc DataBase to fetch album information automatically.";
dict.entries['media']['lxmusic'] = "LXMusic is a GUI application for the Lightweight X11 Desktop Environment (LXDE). It is a minimalist music player based on xmms2 and has server/client design.";
dict.entries['media']['moc'] = "moc (music on console) is a full-screen player designed to be powerful and easy to use. Supported file formats are: MP3, OGG Vorbis, FLAC, OPUS, WAVE, SPEEX, Musepack (MPC), AIFF, AU (and other less popular formats supported by libsndfile).";
dict.entries['media']['musique'] = "Musique unclutters your music listening experience with a clean and innovative interface. It comes with one playlist, plain and simple, but also with graphical display of your albums and artists using pictures downloaded from last.fm. At the same time you can, of course, also browse your music directories and files.";
dict.entries['media']['pmrp'] = "pmrp (Poor Man's Radio Player) is an Internet radio player script written in bash.";
dict.entries['media']['pragha'] = "Pragha is a Lightweight Music Player for GNU/Linux, based on Gtk, sqlite, and completely written in C, constructed to be fast and light.";
dict.entries['media']['qmmp'] = "qmmp is a free and open-source audio player written in C++ which uses Qt library. It officially supports Linux, FreeBSD and Microsoft Windows. The default user interface of qmmp is inspired by Winamp.";
dict.entries['media']['quodlibet'] = "Quod Libet is a music management program. It provides several different ways to view your audio library, as well as support for Internet radio and audio feeds. It has extremely flexible metadata tag editing and searching capabilities, using the same interface as Ex Falso.";
dict.entries['media']['radiotray'] = "This is a simple music streaming player that lives on the system tray. By clicking on the RadioTray icon, you'll be presented with a list of pre-configured online radios. By selecting one of those radios, it will start playing.";
dict.entries['media']['rhythmbox'] = "Rhythmbox is a very easy to use music playing and management program which supports a wide range of audio formats (including mp3 and ogg). Originally inspired by Apple's iTunes, the current version also supports Internet Radio, iPod integration and generic portable audio player support, Audio CD burning, Audio CD playback, music sharing, and Podcasts.";
dict.entries['media']['sayonara'] = "Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt framework. It uses GStreamer as audio backend. Sayonara is open source and uses the GPLv3 license.";
dict.entries['media']['spotifyclient'] = "Spotify streaming music client.";
dict.entries['media']['xmms2'] = "XMMS2 is a redesign of the XMMS music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plug-ins. On top of this, there is a flexible media library to organize your music.";
dict.entries['media']['yarock'] = "Yarock is a modern looking music player, packed with features, that doesn’t depend on any specific desktop environment. Yarock is designed to provide an easy and pretty music browser based on cover art.";
