// English localization file for Multimedia
// Originally created by Piotr "MoroS" Mrożek 2018
// Under the GNU GPL v3
// Last update 2018/12/12 by pavroo
dict.entries['media'] = {};
// multimedia audio players
dict.entries['media']['alsaplayergui'] = "alsaplayer GTK interface.";
dict.entries['media']['amarok'] = "Amarok is a powerful music player with an intuitive interface. It makes playing the music you love and discovering new music easier than ever before and it looks good doing it! Amarok is based on the powerful Qt4 / KDE4 Platform and nicely integrates with KDE desktop.";
dict.entries['media']['ario'] = "Ario is a full featured client for MPD (Music Player Daemon). The interface used to browse the library is inspired by Rhythmbox but Ario aims to be much lighter and faster. It uses GTK2, avahi for MPD server detection and curl to download remote files (like cover arts and lyrics).";
dict.entries['media']['audacious'] = "Small and fast audio player which supports lots of formats. Audacious is a fork of beep-media-player which supports Winamp skins and many codecs.";
dict.entries['media']['cantata'] = "Cantata is a graphical front-end for the music player daemon, MPD. It provides many tools to view and manage the music collection.";
dict.entries['media']['clementine'] = "Clementine is a multiplatform music player focusing on a fast and easy-to-use interface for searching and playing your music.";
dict.entries['media']['cmus'] = "C* Music Player is a modular and very configurable ncurses-based audio player. It has some interesting features like configurable colorscheme, mp3 and ogg streaming, it can be controlled with an UNIX socket, filters, album/artists sorting and a vi-like configuration interface.";
dict.entries['media']['deadbeef'] = "DeaDBeeF is an audio player for GNU/Linux, *BSD, OpenSolaris, Mac OS X, and other UNIX-like systems.";
dict.entries['media']['deepinmusic'] = "Deepin-UI based, GStreamer front-end, with features likes search music by pinyin,quanpin, colorful lyrics supports, and more powerful functions you will found.";
dict.entries['media']['dradio'] = "Dradio is a terminal based frontend to MPlayer that collects the available channels/podcasts for convenient browsing.";
dict.entries['media']['exaile'] = "Exaile is a media player which incorporates many of the cool things from Amarok (and other media players) like automatic fetching of album art, handling of large libraries, lyrics fetching, artist/album information via Wikipedia, last.fm support, and optional iPod support.";
dict.entries['media']['gmerlin'] = "Gmerlin is a multiformat media player with tree-like virtual directory structure, where you can save your files, webstreams or whatever. It handles even large media collections gracefully. Hardware devices appear also in the tree so you can open Audio-CDs, (S)VCDs, DVDs and DVB-broadcasts.";
dict.entries['media']['gmusicbrowser'] = "gmusicbrowser is a powerful graphical browser which supports libraries with a very large number of songs (over 10,000). It can use multiple inputs and has native support for MP3, Ogg, and FLAC files. It also supports mass-renaming and mass-retagging of a song library, multiple genres per song, ratings, and customizable labels.";
dict.entries['media']['gnomemusic'] = "Music is the new GNOME music playing application aiming at being a simple and elegant replacement for using Files to show the Music directory. Objectives includes listening to local and online/cloud collections, listen to music on attached devices, listen to music shared by friends, listen to audiobooks, a player for DLNA media servers, share music, upload music and select favorites.";
dict.entries['media']['gradio'] = "A GTK3 app for finding and listening to internet radio stations.";
dict.entries['media']['jajuk'] = "Jajuk is software that organizes and plays music. Jajuk is designed to be intuitive, fast and provide multiple ways to perform the same operation. It is a fully-featured application geared towards advanced users with very large or scattered music collections.";
dict.entries['media']['juk'] = "JuK is a free software audio player by KDE, the default player since K Desktop Environment 3.2. JuK supports collections of MP3, Ogg Vorbis, and FLAC audio files.";
dict.entries['media']['kradio4'] = "KRadio is a comfortable radio application for KDE 4.x with support for V4L and V4L2 radio cards drivers.";
dict.entries['media']['kscd'] = "KsCD is an audio CD player. It uses the Compact Disc DataBase to fetch album information automatically.";
dict.entries['media']['lxmusic'] = "LXMusic is a GUI application for the Lightweight X11 Desktop Environment (LXDE). It is a minimalist music player based on xmms2 and has server/client design.";
dict.entries['media']['moc'] = "moc (music on console) is a full-screen player designed to be powerful and easy to use. Supported file formats are: MP3, OGG Vorbis, FLAC, OPUS, WAVE, SPEEX, Musepack (MPC), AIFF, AU (and other less popular formats supported by libsndfile).";
dict.entries['media']['mpd'] = "Music Player Daemon (MPD) is a server that allows remote access for playing audio files (Ogg-Vorbis, FLAC, MP3, Wave, and AIFF), streams (Ogg-Vorbis, MP3) and managing playlists. Gapless playback, buffered output, and crossfading support is also included. The design focus is on integrating a computer into a stereo system that provides control for music playback over a TCP/IP network.";
dict.entries['media']['musique'] = "Musique unclutters your music listening experience with a clean and innovative interface. It comes with one playlist, plain and simple, but also with graphical display of your albums and artists using pictures downloaded from last.fm. At the same time you can, of course, also browse your music directories and files.";
dict.entries['media']['ncmpc'] = "This package contains a text-mode client for MPD, the Music Player Daemon. Its goal is to provide a keyboard oriented and consistent interface to MPD, without wasting resources.";
dict.entries['media']['pmrp'] = "pmrp (Poor Man's Radio Player) is an Internet radio player script written in bash.";
dict.entries['media']['pragha'] = "Pragha is a Lightweight Music Player for GNU/Linux, based on Gtk, sqlite, and completely written in C, constructed to be fast and light.";
dict.entries['media']['qmmp'] = "qmmp is a free and open-source audio player written in C++ which uses Qt library. It officially supports Linux, FreeBSD and Microsoft Windows. The default user interface of qmmp is inspired by Winamp.";
dict.entries['media']['quodlibet'] = "Quod Libet is a music management program. It provides several different ways to view your audio library, as well as support for Internet radio and audio feeds. It has extremely flexible metadata tag editing and searching capabilities, using the same interface as Ex Falso.";
dict.entries['media']['radio'] = "This package provides a ncurses-based radio application. It supports the video4linux API.";
dict.entries['media']['radiotray'] = "This is a simple music streaming player that lives on the system tray. By clicking on the RadioTray icon, you'll be presented with a list of pre-configured online radios. By selecting one of those radios, it will start playing.";
dict.entries['media']['rhythmbox'] = "Rhythmbox is a very easy to use music playing and management program which supports a wide range of audio formats (including mp3 and ogg). Originally inspired by Apple's iTunes, the current version also supports Internet Radio, iPod integration and generic portable audio player support, Audio CD burning, Audio CD playback, music sharing, and Podcasts.";
dict.entries['media']['sayonara'] = "Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt framework. It uses GStreamer as audio backend. Sayonara is open source and uses the GPLv3 license.";
dict.entries['media']['sonata'] = "Sonata is a lightweight GTK+ music client for the Music Player Daemon (MPD). It aims to be efficient (no toolbar, main menu, or statusbar), user-friendly, and clean.";
dict.entries['media']['spotifyclient'] = "Spotify streaming music client.";
dict.entries['media']['xmms2'] = "XMMS2 is a redesign of the XMMS music player. It features a client-server model, allowing multiple (even simultaneous!) user interfaces, both textual and graphical. All common audio formats are supported using plug-ins. On top of this, there is a flexible media library to organize your music.";
dict.entries['media']['yarock'] = "Yarock is a modern looking music player, packed with features, that doesn’t depend on any specific desktop environment. Yarock is designed to provide an easy and pretty music browser based on cover art.";
// multimedia codecs
dict.entries['media']['faac'] = "The FAAC project includes the AAC encoder FAAC and decoder FAAD2. It supports several MPEG-4 object types (LC, Main, LTP, HE AAC, PS) and file formats (ADTS AAC, raw AAC, MP4), multichannel and gapless en/decoding as well as MP4 metadata tags. The codecs are compatible with standard-compliant audio applications using one or more of these profiles.";
dict.entries['media']['ffmpeg'] = "FFmpeg is the leading multimedia framework, able to decode, encode, transcode, mux, demux, stream, filter and play pretty much anything that humans and machines have created. It supports the most obscure ancient formats up to the cutting edge.";
dict.entries['media']['flac'] = "FLAC stands for Free Lossless Audio Codec. Grossly oversimplified, FLAC is similar to MP3, but lossless.";
dict.entries['media']['flashplayerchromium'] = "Flash Player for Chromium (Pepper) lets you experience animation and entertainment in chromium based web browsers.";
dict.entries['media']['flashplayermozilla'] = "Adobe Flash Player lets you experience animation and entertainment in Mozilla based web browsers.";
dict.entries['media']['gstreameralsa'] = "This package contains the GStreamer plugin for the ALSA library. ALSA is the Advanced Linux Sound Architecture.";
dict.entries['media']['gstreamerlibav'] = "This GStreamer plugin supports a large number of audio and video compression formats through the use of the libav library. The plugin contains GStreamer elements for encoding 40+ formats (MPEG, DivX, MPEG4, AC3, DV, ...), decoding elements for decoding 90+ formats (AVI, MPEG, OGG, Matroska, ASF, ...), demuxing 30+ formats.";
dict.entries['media']['gstreamerpluginsbad'] = "GStreamer Bad Plug-ins is a set of plug-ins that aren't up to par compared to the rest. They might be close to being good quality, but they're missing something - be it a good code review, some documentation, a set of tests, a real live maintainer, or some actual wide use.";
dict.entries['media']['gstreamerpluginsbase'] = "This package contains the GStreamer plugins from the 'base' set, an essential exemplary set of elements.";
dict.entries['media']['gstreamerpluginsgood'] = "This package contains the GStreamer plugins from the 'good' set, a set of good-quality plug-ins under the LGPL license.";
dict.entries['media']['gstreamerpluginsugly'] = "This package contains plugins from the 'ugly' set, a set of good-quality plug-ins that might pose distribution problems.";
dict.entries['media']['gstreamerpulseaudio'] = "This package contains the GStreamer plugin for PulseAudio, a sound server for POSIX and WIN32 systems.";
dict.entries['media']['lame'] = "LAME (recursive acronym for LAME Ain't an MP3 Encoder) is a research project for learning about and improving MP3 encoding technology. LAME includes an MP3 encoding library, a simple frontend application, and other tools for sound analysis, as well as convenience tools.";
dict.entries['media']['libdvdpkg'] = "This package provides libraries that are needed for playing video DVDs with a media player (such as VLC, SMplayer, Totem, etc.). It automates the process of downloading source files, compiling them, and installing the binary packages.";
dict.entries['media']['libdvdread4'] = "libdvdread provides the functionality that is required to access many DVDs. It parses IFO files, reads NAV-blocks, and performs CSS authentication and descrambling.";
dict.entries['media']['mencoder'] = "This package contains mencoder, a simple movie encoder, designed to encode MPlayer-playable movies (AVI/ASF/OGG/DVD/VCD/VOB/MPG/MOV/VIV/FLI/RM/NUV/NET) to other MPlayer-playable formats. It can encode with various codecs, like DivX4 (1 or 2 passes), libavcodec, PCM/MP3/VBRMP3 audio. Also has stream copying and video resizing capabilities.";
dict.entries['media']['mkvtoolnix'] = "Matroska is a multimedia container format, based on EBML (Extensible Binary Meta Language), which is a kind of binary XML. These tools allow one to manipulate Matroska files.";
dict.entries['media']['mpg123'] = "mpg123 is a real time MPEG 1.0/2.0/2.5 audio player/decoder for layers 1, 2 and 3 (MPEG 1.0 layer 3 also known as MP3). This package contains output plugins for several audio systems, including OSS4, the Advanced Linux Sound Architecture (ALSA), JACK, PortAudio, PulseAudio, OpenAL and the Network Audio System (NAS).";
dict.entries['media']['ogmtools'] = "Tools for manipulating Ogg multimedia streams.";
dict.entries['media']['twolame'] = "TwoLAME is an optimized MPEG Audio Layer 2 encoder. It is based on tooLAME by Mike Cheng, which in turn is based upon the ISO dist10 code and portions of LAME. Because of patent issues surrounding the MPEG Audio Layer 3 (MP3) encoders, the ability of most MPEG Audio players to play layer 2 files, and the similarity in command-line syntax and API, TwoLAME makes a very good drop-in replacement for LAME or other layer 3 encoders.";
dict.entries['media']['vorbistools'] = "vorbis-tools contains oggenc (an encoder), ogg123 (a playback tool), ogginfo (displays ogg information), oggdec (decodes ogg files), vcut (ogg file splitter), and vorbiscomment (ogg comment editor).";
dict.entries['media']['x264'] = "x264 is an advanced commandline encoder for creating H.264 (MPEG-4 AVC) video streams.";
dict.entries['media']['x265'] = "x265 is a commandline encoder for creating H.265/High Efficiency Video Coding (HEVC) video streams.";
// multimedia others
dict.entries['media']['kazam'] = "Kazam provides a well designed and easy to use interface for capturing screencasts and screenshots. It can record desktop video and multiple audio streams simultaneously with control over audio levels and the screen region being captured.";
dict.entries['media']['lxmms2'] = "lxmms2 is a tiny XMMS2 client to control XMMS2 with a LIRC compatible remote control.";
dict.entries['media']['vokoscreen'] = "vokoscreen can be used to record educational videos, live recordings of browser, installation, videoconferences, etc. You can capture an alone video or video and sound (via ALSA or PulseAudio).";
// multimedia video players
dict.entries['media']['gnomempv'] = "GNOME MPV is a simple GTK+ frontend for mpv. GNOME MPV interacts with mpv via the client API exported by libmpv, allowing access to mpv's powerful playback capabilities.";
dict.entries['media']['kmplayer'] = "MPlayer is a free and expanded multimedia player. It supports all the most popular audio and video formats (including AVI, MP4, MPEG1, MPEG2, MPEG4, MOV, RMVB, WMV, MP3, OGG and WMA) and plays DVD-Video and Blu-ray discs without any problems.";
dict.entries['media']['kodi'] = "Kodi, formerly known as XBMC is an award winning free and open source software media-player and entertainment hub for all your digital media. It supports an almost endless range of remote controls, and combined with its beautiful interface and powerful skinning engine, Kodi feels very natural to use from the couch and is the ideal solution for your home theater.";
dict.entries['media']['motionbox'] = "MotionBox is a Video Browser for Motion Freedom. Built to access and traverse decentralized video sources. Built to load and play multiple video resources.";
dict.entries['media']['mplayer'] = "MPlayer plays most MPEG, VOB, AVI, Ogg/OGM, VIVO, ASF/WMA/WMV, QT/MOV/MP4, FLI, RM, NuppelVideo, yuv4mpeg, FILM, RoQ, PVA files, supported by many native, XAnim, RealPlayer, and Win32 DLL codecs. It can also play VideoCD, SVCD, DVD, 3ivx, RealMedia, and DivX movies.";
dict.entries['media']['mpv'] = "mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types.";
dict.entries['media']['parole'] = "Parole is a media player for the Xfce desktop environment, written using the GStreamer framework. Parole features playback of local media files, including video with subtitles support, DVD/CD and live streams; it is also extensible via plugins.";
dict.entries['media']['rage'] = "Video Player for Enlightenment.";
dict.entries['media']['smplayer'] = "Qt5 front-end for mplayer and forks, with basic features like playing videos, DVDs, and VCDs to more advanced features like support for MPlayer filters and more. One of the most interesting features of SMPlayer: it remembers the settings of all files you play.";
dict.entries['media']['smtube'] = "SMTube is a stand-alone graphical application which allows one to search and download Youtube videos. Although it is part of the SMPlayer project, it can be used with any multimedia player such as MPlayer, MPlayer2, VLC, Totem or Gnome-MPlayer.";
dict.entries['media']['totem'] = "Totem is a simple yet featureful media player for GNOME which can read a large number of file formats.";
dict.entries['media']['vlc'] = "VLC is the VideoLAN project's media player. It plays MPEG, MPEG-2, MPEG-4, DivX, MOV, WMV, QuickTime, WebM, FLAC, MP3, Ogg/Vorbis files, DVDs, VCDs, podcasts, and multimedia streams from various network sources. VLC can also be used as a streaming server that duplicates the stream it reads and multicasts them through the network to other clients, or serves them through HTTP.";
dict.entries['media']['xineconsole'] = "The xine video player, console user interface. This package contains additional front ends, aaxine, cacaxine and fbxine which run even on the console, so you can use it to watch DVDs even in an xterm.";
dict.entries['media']['xineui'] = "The xine video player, graphical user interface for the libxine video player library. It provides xine, a skin based media player that can play all the audio/video formats that libxine supports. Currently, this includes MPEG1/2, some AVI and Quicktime files, some network streaming methods and disc based media (VCD, SVCD, DVD).";
