// Polish localization file for Multimedia
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2018/12/10 by pavroo
dict.entries['media'] = {};
// multimedia audio players
dict.entries['media']['alsaplayergui'] = "Interfejs GTK do alsaplayer.";
dict.entries['media']['amarok'] = "Amarok jest wszechstronnym odtwarzaczem muzycznym z intuicyjnym interfejsem. Sprawia, że odtwarzanie ulubionej muzyki oraz odkrywanie nowej jest prostsze, niż kiedykolwiek wcześniej, a przy okazji świetnie wygląda. Amarok jest oparty na wszechstronnej platformie technologicznej Qt4 / KDE4 i dobrze integruje się ze środowiskiem KDE.";
dict.entries['media']['audacious'] = "Mały i szybki odtwarzacz audio obsługujący wiele formatów. Audacious jest odgałęzieniem Beep Media Playera z obsługą skórek Winampa i wielu kodeków.";
dict.entries['media']['cantata'] = "Cantata jest graficznym interfejsem dla demona muzyki MPD. Zapewnia wiele narzędzi do przeglądania kolekcji muzycznej i zarządzania nią.";
dict.entries['media']['clementine'] = "Clementine to wieloplatformowy odtwarzacz muzyczny skupiający się na szybkim i łatwym w użyciu interfejsie do wyszukiwania i odtwarzania muzyki.";
dict.entries['media']['cmus'] = "C* Music Player to modułowy i bardzo konfigurowalny odtwarzacz audio oparty na ncurses. Ma kilka interesujących funkcji, takich jak konfigurowalne kolory, streaming mp3 i ogg, można go kontrolować za pomocą gniazda UNIX, filtrów, sortowania albumów / artystów i interfejsu konfiguracyjnego w stylu vi.";
dict.entries['media']['deadbeef'] = "DeaDBeeF to odtwarzacz audio dla systemów GNU / Linux, * BSD, OpenSolaris, Mac OS X i innych systemów typu UNIX.";
dict.entries['media']['dradio'] = "Dradio to działające w konsoli tekstowej nakładka na MPlayera, która zbiera dostępne kanały / podcasty w celu wygodnego przeglądania.";
dict.entries['media']['exaile'] = "Exaile jest odtwarzaczem multimediów, łączącym wiele ciekawych funkcji z Amaroka (oraz innych odtwarzaczy), jak np.: automatyczne pobieranie okładek albumów, obsługę dużych bibliotek multimediów, tekstów utworów, informacji o artyście bądź albumie z Wikipedii, obsługę last.fm oraz opcjonalnie iPodów.";
dict.entries['media']['gmerlin'] = "Gmerlin to wieloformatowy odtwarzacz multimedialny o podobnej do drzewa wirtualnej strukturze katalogów, w której można zapisywać pliki, strumienie internetowe czy cokolwiek innego. Odtwarzacz ten bezproblemowo obsługuje ogromne kolekcje multimedialne. W drzewie katalogów występują również urządzenia sprzętowe, dzięki czemu można otwierać płyty Audio-CD, (S)VCD, DVD oraz audycje DVB.";
dict.entries['media']['gmusicbrowser'] = "gmusicbrowser to zaawansowana przeglądarka muzyki obsługująca biblioteki z bardzo dużą liczbą utworów (ponad 10 000). Może korzystać z wielu wejść i ma natywną obsługę plików MP3, Ogg i FLAC. Obsługuje również masową zmianę nazwy i retagowanie masowe biblioteki utworów, wielu gatunków na utwór, ocen i dostosowywanych etykiet.";
dict.entries['media']['gnomemusic'] = "GNOME Music jest aplikacją do odtwarzania muzyki,  mającą na celu być prostym i eleganckim zamiennikiem używania plików do wyświetlania katalogu Muzyka. Cele aplikacji obejmują słuchanie lokalnych i internetowych / chmurowych kolekcji, na podłączonych urządzeniach, udostępnionej przez znajomych, odsłuchiwanie audiobooków, odtwarzacz serwerów multimedialnych DLNA, udostępnianie muzyki, przesyłanie muzyki i wybieranie ulubionych.";
dict.entries['media']['gradio'] = "Aplikacja GTK3 do wyszukiwania i słuchania internetowych stacji radiowych.";
dict.entries['media']['jajuk'] = "Jajuk służy do organizowania i odtwarzania muzyki. Został zaprojektowany jako szybki i intuicyjny program, który zapewnia wiele sposobów wykonywania tej samej operacji. Jest on w pełni funkcjonalny, ukierunkowany na zaawansowanych użytkowników, posiadających wielką lub obszerną kolekcję plików muzycznych.";
dict.entries['media']['juk'] = "JuK jest wolnym odtwarzaczem audio rozwijanym przez KDE i  domyślnym odtwarzacz od K Desktop Environment od wersji 3.2. JuK obsługuje kolekcje plików MP3, Ogg Vorbis i FLAC.";
dict.entries['media']['kscd'] = "KsCD to odtwarzacz płyt audio CD. Korzysta z Compact Disc DataBase do automatycznego pobierania informacji o albumie.";
dict.entries['media']['lxmusic'] = "LXMusic jest aplikacją z graficznym interfejsem użytkownika do LXDE (Lightweight X11 Desktop Environment). Jest to minimalistyczny odtwarzacz muzyczny oparty na xmms2, pracujący w modelu klient-serwer.";
dict.entries['media']['moc'] = "Program moc (music on console) jest pełnoekranowym, funkcjonalnym i łatwym w użyciu odtwarzaczem muzycznym. Program obsługuje następujące formaty plików: MP3, OGG Vorbis, FLAC, OPUS, WAVE, SPEEX, Musepack (MPC), AIFF, AU (i inne mniej popularne, obsługiwane przez libsndfile).";
dict.entries['media']['musique'] = "Musique upraszcza słuchanie muzyki dzięki czystemu i innowacyjnemu interfejsowi. Zawiera jedną prostą playlistę, ale także graficzne wyświetlanie twoich albumów i wykonawców za pomocą zdjęć pobranych z last.fm. W tym samym czasie możesz oczywiście przeglądać katalogi muzyczne i pliki.";
dict.entries['media']['pmrp'] = "pmrp (Poor Man's Radio Player) to skrypt radia internetowego napisany w bashu.";
dict.entries['media']['pragha'] = "Pragha jest lekkim odtwarzaczem muzycznym dla systemu GNU / Linux, opartym na Gtk, sqlite i całkowicie napisanym w języku C, skonstruowanym tak, aby był szybki i lekki.";
dict.entries['media']['qmmp'] = "qmmp to darmowy i otwarty odtwarzacz audio napisany w C ++, który używa biblioteki Qt. Oficjalnie obsługuje systemy Linux, FreeBSD i Microsoft Windows. Domyślny interfejs użytkownika qmmp jest zainspirowany przez Winampa.";
dict.entries['media']['quodlibet'] = "Quod Libet to program do zarządzania muzyką. Zapewnia kilka różnych sposobów przeglądania biblioteki audio, a także obsługę radia internetowego i kanałów dźwiękowych. Posiada niezwykle elastyczne możliwości edycji i przeszukiwania tagów metadanych przy użyciu tego samego interfejsu co Ex Falso.";
dict.entries['media']['radiotray'] = "Jest to prosty odtwarzacz muzyki strumieniowej, który działa na pasku zadań. Kliknięcie ikony RadioTray spowoduje wyświetlenie wstępnie skonfigurowanych list radia internetowego. Po wybraniu jednej z list zacznie się odtwarzanie.";
dict.entries['media']['rhythmbox'] = "Rhythmbox jest bardzo prostym w obsłudze programem muzycznym umożliwiającym odtwarzanie plików muzycznych oraz zarządzanie nimi, wspiera wiele formatów (m.in. mp3 czy ogg). Pierwotnie wzorowany na programie iTunes firmy Apple, obecna wersja wspiera również obsługę e-Radia, integrację z iPodem oraz innymi przenośnymi odtwarzaczami, nagrywanie płyt Audio, odtwarzanie płyt Audio, współdzielenie plików muzycznych oraz Podcasty";
dict.entries['media']['sayonara'] = "Sayonara to mały, klarowny i szybki odtwarzacz audio dla systemu Linux napisany w C ++, wspierany przez framework Qt. Używa GStreamer jako wyjścia audio. Sayonara jest aplikacją open source wydaną na licencji GPLv3.";
dict.entries['media']['spotifyclient'] = "Klienta muzyki strumieniowej Spotify.";
dict.entries['media']['xmms2'] = "XMMS2 to unowocześniony odtwarzacz muzyczny XMMS. Działa w modelu klient-serwer, umożliwiając wiele (nawet jednoczesnych!) interfejsów użytkownika, zarówno tekstowych, jak i graficznych. Wszystkie popularne formaty audio są obsługiwane za pomocą wtyczek. Oprócz tego, dostępna jest elastyczna biblioteka multimediów do porządkowania muzyki.";
dict.entries['media']['yarock'] = "Yarock to nowoczesny, pełen funkcji odtwarzacz muzyki, który nie zależy od konkretnego środowiska graficznego. Yarock ma zapewniać łatwą i ładną przeglądarkę muzyczną opartą na okładce.";
