// Polish localization file for Multimedia
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2019/01/11 by pavroo
dict.entries['media'] = {};
// multimedia audio players
dict.entries['media']['alsaplayergui'] = "Interfejs GTK dla alsaplayer.";
dict.entries['media']['amarok'] = "Amarok jest wszechstronnym odtwarzaczem muzycznym z intuicyjnym interfejsem. Sprawia, że odtwarzanie ulubionej muzyki oraz odkrywanie nowej jest prostsze, niż kiedykolwiek wcześniej, a przy okazji świetnie wygląda. Amarok jest oparty na wszechstronnej platformie technologicznej Qt4 / KDE4 i dobrze integruje się ze środowiskiem KDE.";
dict.entries['media']['ario'] = "Ario jest w pełni funkcjonalnym klientem MPD (Music Player Daemon). Interfejs użyty do przeglądania bibliotek jest inspirowany na Rhythmboksie, od którego Ario wydaje się być znacznie lżejsze i szybsze. Używa GTK2, avahi do wykrywania serwera MPD i curl do pobierania zdalnych plików (np. okładek płyt i tekstów piosenek).";
dict.entries['media']['audacious'] = "Mały i szybki odtwarzacz audio obsługujący wiele formatów. Audacious jest odgałęzieniem Beep Media Playera z obsługą skórek Winampa i wielu kodeków.";
dict.entries['media']['cantata'] = "Cantata jest graficznym interfejsem dla demona muzyki MPD. Zapewnia wiele narzędzi do przeglądania kolekcji muzycznej i zarządzania nią.";
dict.entries['media']['clementine'] = "Clementine to wieloplatformowy odtwarzacz muzyczny skupiający się na szybkim i łatwym w użyciu interfejsie do wyszukiwania i odtwarzania muzyki.";
dict.entries['media']['cmus'] = "C* Music Player to modułowy i bardzo konfigurowalny odtwarzacz audio oparty na ncurses. Ma kilka interesujących funkcji, takich jak konfigurowalne kolory, streaming mp3 i ogg, można go kontrolować za pomocą gniazda UNIX, filtrów, sortowania albumów / artystów i interfejsu konfiguracyjnego w stylu vi.";
dict.entries['media']['deadbeef'] = "DeaDBeeF to odtwarzacz audio dla systemów GNU / Linux, * BSD, OpenSolaris, Mac OS X i innych systemów typu UNIX.";
dict.entries['media']['deepinmusic'] = "Oparte na Deepin-UI, front-end dla GStreamer, z funkcjami takim jak wyszukiwanie muzyki przez pinyin, quanpin i wiele innych.";
dict.entries['media']['dradio'] = "Dradio to działające w konsoli tekstowej nakładka na MPlayera, która zbiera dostępne kanały / podcasty w celu wygodnego przeglądania.";
dict.entries['media']['exaile'] = "Exaile jest odtwarzaczem multimediów, łączącym wiele ciekawych funkcji z Amaroka (oraz innych odtwarzaczy), jak np.: automatyczne pobieranie okładek albumów, obsługę dużych bibliotek multimediów, tekstów utworów, informacji o artyście bądź albumie z Wikipedii, obsługę last.fm oraz opcjonalnie iPodów.";
dict.entries['media']['gmerlin'] = "Gmerlin to wieloformatowy odtwarzacz multimedialny o podobnej do drzewa wirtualnej strukturze katalogów, w której można zapisywać pliki, strumienie internetowe czy cokolwiek innego. Odtwarzacz ten bezproblemowo obsługuje ogromne kolekcje multimedialne. W drzewie katalogów występują również urządzenia sprzętowe, dzięki czemu można otwierać płyty Audio-CD, (S)VCD, DVD oraz audycje DVB.";
dict.entries['media']['gmusicbrowser'] = "gmusicbrowser to zaawansowana przeglądarka muzyki obsługująca biblioteki z bardzo dużą liczbą utworów (ponad 10 000). Może korzystać z wielu wejść i ma natywną obsługę plików MP3, Ogg i FLAC. Obsługuje również masową zmianę nazwy i retagowanie masowe biblioteki utworów, wielu gatunków na utwór, ocen i dostosowywanych etykiet.";
dict.entries['media']['gnomemusic'] = "GNOME Music jest aplikacją do odtwarzania muzyki,  mającą na celu być prostym i eleganckim zamiennikiem używania plików do wyświetlania katalogu Muzyka. Cele aplikacji obejmują słuchanie lokalnych i internetowych / chmurowych kolekcji, na podłączonych urządzeniach, udostępnionej przez znajomych, odsłuchiwanie audiobooków, odtwarzacz serwerów multimedialnych DLNA, udostępnianie muzyki, przesyłanie muzyki i wybieranie ulubionych.";
dict.entries['media']['gradio'] = "Aplikacja GTK3 do wyszukiwania i słuchania internetowych stacji radiowych.";
dict.entries['media']['jajuk'] = "Jajuk służy do organizowania i odtwarzania muzyki. Został zaprojektowany jako szybki i intuicyjny program, który zapewnia wiele sposobów wykonywania tej samej operacji. Jest on w pełni funkcjonalny, ukierunkowany na zaawansowanych użytkowników, posiadających wielką lub obszerną kolekcję plików muzycznych.";
dict.entries['media']['juk'] = "JuK jest wolnym odtwarzaczem audio rozwijanym przez KDE i  domyślnym odtwarzacz od K Desktop Environment od wersji 3.2. JuK obsługuje kolekcje plików MP3, Ogg Vorbis i FLAC.";
dict.entries['media']['kradio4'] = "KRadio to wygodna aplikacja radiowa dla KDE 4.x z obsługą sterowników kart radiowych V4L i V4L2.";
dict.entries['media']['kscd'] = "KsCD to odtwarzacz płyt audio CD. Korzysta z Compact Disc DataBase do automatycznego pobierania informacji o albumie.";
dict.entries['media']['lxmusic'] = "LXMusic jest aplikacją z graficznym interfejsem użytkownika do LXDE (Lightweight X11 Desktop Environment). Jest to minimalistyczny odtwarzacz muzyczny oparty na xmms2, pracujący w modelu klient-serwer.";
dict.entries['media']['moc'] = "Program moc (music on console) jest pełnoekranowym, funkcjonalnym i łatwym w użyciu odtwarzaczem muzycznym. Program obsługuje następujące formaty plików: MP3, OGG Vorbis, FLAC, OPUS, WAVE, SPEEX, Musepack (MPC), AIFF, AU (i inne mniej popularne, obsługiwane przez libsndfile).";
dict.entries['media']['mpd'] = "Music Player Daemon (MPD) to serwer umożliwiający zdalny dostęp do odtwarzania plików audio (Ogg-Vorbis, FLAC, MP3, Wave i AIFF), strumieni (Ogg-Vorbis, MP3) i zarządzania listami odtwarzania. Uwzględniono również odtwarzanie bez przerw, zbuforowane wyjście i obsługę przechodzenia między stopami. Projekt skupia się na zintegrowaniu komputera z systemem stereo, który zapewnia kontrolę odtwarzania muzyki przez sieć TCP / IP.";
dict.entries['media']['musique'] = "Musique upraszcza słuchanie muzyki dzięki czystemu i innowacyjnemu interfejsowi. Zawiera jedną prostą playlistę, ale także graficzne wyświetlanie twoich albumów i wykonawców za pomocą zdjęć pobranych z last.fm. W tym samym czasie możesz oczywiście przeglądać katalogi muzyczne i pliki.";
dict.entries['media']['ncmpc'] = "Ten pakiet zawiera klienta trybu tekstowego dla MPD, demona odtwarzacza muzyki. Jego celem jest zapewnienie zorientowanego na klawiaturę i spójnego interfejsu do MPD, bez marnowania zasobów.";
dict.entries['media']['pmrp'] = "pmrp (Poor Man's Radio Player) to skrypt radia internetowego napisany w bashu.";
dict.entries['media']['pragha'] = "Pragha jest lekkim odtwarzaczem muzycznym dla systemu GNU / Linux, opartym na Gtk, sqlite i całkowicie napisanym w języku C, skonstruowanym tak, aby był szybki i lekki.";
dict.entries['media']['qmmp'] = "qmmp to darmowy i otwarty odtwarzacz audio napisany w C ++, który używa biblioteki Qt. Oficjalnie obsługuje systemy Linux, FreeBSD i Microsoft Windows. Domyślny interfejs użytkownika qmmp jest zainspirowany przez Winampa.";
dict.entries['media']['quodlibet'] = "Quod Libet to program do zarządzania muzyką. Zapewnia kilka różnych sposobów przeglądania biblioteki audio, a także obsługę radia internetowego i kanałów dźwiękowych. Posiada niezwykle elastyczne możliwości edycji i przeszukiwania tagów metadanych przy użyciu tego samego interfejsu co Ex Falso.";
dict.entries['media']['radio'] = "Pakiet dostarcza aplikację radio opartą na bibliotece ncurses. Obsługuje API Video4Linux.";
dict.entries['media']['radiotray'] = "Jest to prosty odtwarzacz muzyki strumieniowej, który działa na pasku zadań. Kliknięcie ikony RadioTray spowoduje wyświetlenie wstępnie skonfigurowanych list radia internetowego. Po wybraniu jednej z list zacznie się odtwarzanie.";
dict.entries['media']['rhythmbox'] = "Rhythmbox jest bardzo prostym w obsłudze programem muzycznym umożliwiającym odtwarzanie plików muzycznych oraz zarządzanie nimi, wspiera wiele formatów (m.in. mp3 czy ogg). Pierwotnie wzorowany na programie iTunes firmy Apple, obecna wersja wspiera również obsługę e-Radia, integrację z iPodem oraz innymi przenośnymi odtwarzaczami, nagrywanie płyt Audio, odtwarzanie płyt Audio, współdzielenie plików muzycznych oraz Podcasty";
dict.entries['media']['sayonara'] = "Sayonara to mały, klarowny i szybki odtwarzacz audio dla systemu Linux napisany w C ++, wspierany przez framework Qt. Używa GStreamer jako wyjścia audio. Sayonara jest aplikacją open source wydaną na licencji GPLv3.";
dict.entries['media']['sonata'] = "Sonata jest lekkim klientem muzycznym GTK+ dla Music Player Daemona (MPD). Jej celem jest wydajność (bez paska narzędzi, głównego menu czy też paska stanu), przyjazność użytkownikowi i prostota.";
dict.entries['media']['spotifyclient'] = "Klienta muzyki strumieniowej Spotify.";
dict.entries['media']['xmms2'] = "XMMS2 to unowocześniony odtwarzacz muzyczny XMMS. Działa w modelu klient-serwer, umożliwiając wiele (nawet jednoczesnych!) interfejsów użytkownika, zarówno tekstowych, jak i graficznych. Wszystkie popularne formaty audio są obsługiwane za pomocą wtyczek. Oprócz tego, dostępna jest elastyczna biblioteka multimediów do porządkowania muzyki.";
dict.entries['media']['yarock'] = "Yarock to nowoczesny, pełen funkcji odtwarzacz muzyki, który nie zależy od konkretnego środowiska graficznego. Yarock ma zapewniać łatwą i ładną przeglądarkę muzyczną opartą na okładce.";
// multimedia burn cd/dvd
dict.entries['media']['brasero'] = "Brasero jest prostą aplikacją do nagrywania, kopiowania i wymazywania nośników CD i DVD: audio, wideo lub danych. Umożliwia między innymi: Nagrywanie w locie, Nagrywanie wielosesyjne, Konwertowanie w locie muzycznych list odtwarzania we wszystkich formatach obsługiwanych przez GStreamera.";
dict.entries['media']['cdrdao'] = "Nagrywanie w trybie Disk-At-Once zapisuje cały dysk, tzn. obszar lead-in, jedną lub więcej ścieżek i lead-out w jednym kroku. Często używany tryb Track-At-Once (TAO) zapisuje ścieżki niezależnie, co wymaga powiązania bloków pomiędzy dwoma ścieżkami. Dobrym przykładem użycia tej metody jest kopiowanie płyty CD z wieloma ścieżkami np. większości płyt audio.";
dict.entries['media']['k3b'] = "Zaawansowana aplikacja do nagrywania płyt CD/DVD. K3b zapewnia komfortowy interfejs użytkownika do wykonywania większości zadań związanych z nagrywaniem płyt CD/DVD. O ile doświadczony użytkownik może wpływać na wszystkie etapy procesu nagrywania, o tyle początkujący może pozostać przy ustawieniach automatycznych oraz rozsądnych domyślnych wartościach pozwalających na szybki start.";
dict.entries['media']['simpleburn'] = "Minimalistyczna aplikacja do wypalania i wypakowywania płyt CD i DVD.";
dict.entries['media']['xfburn'] = "Xfburn jest narzędziem, które pomaga nagrywać płyty CD i DVD. Nieźle wpasowuje się środowisko graficzne Xfce, ale może być używane z innym środowiskiem.";
// multimedia codecs
dict.entries['media']['faac'] = "Projekt FAAC obejmuje koder AAC FAAC i dekoder FAAD2. Obsługuje kilka typów obiektów MPEG-4 (LC, Main, LTP, HE AAC, PS) i formaty plików (ADTS AAC, raw AAC, MP4), wielokanałowe i pozbawione przerw kodowanie / dekodowanie oraz znaczniki metadanych MP4. Kodeki są zgodne z aplikacjami audio zgodnymi ze standardami, wykorzystującymi jeden lub więcej z tych profili.";
dict.entries['media']['ffmpeg'] = "FFmpeg to wiodąca platforma multimedialna, zdolna do dekodowania, kodowania, transkodowania, multipleksu, demultipleksowania, streamowania, filtrowania i odtwarzania niemal wszystkiego, co stworzyli ludzie i maszyny. Obsługuje najbardziej nieznane starożytne formaty aż do nowatorskich rozwiązań.";
dict.entries['media']['flac'] = "FLAC oznacza Free Lossless Audio Codec. Upraszczając, FLAC jest podobny do MP3, ale bezstratny.";
dict.entries['media']['flashplayerchromium'] = "Flash Player dla Chromium (Pepper) umożliwia oglądanie animacji i rozrywki w przeglądarkach opartych na Chromium.";
dict.entries['media']['flashplayermozilla'] = "Ten pakiet zawiera wtyczkę GStreamera dla biblioteki ALSA. ALSA jest akronimem utworzonym z wyrazów Advanced Linux Sound Architecture.";
dict.entries['media']['gstreameralsa'] = "Ten pakiet zawiera wtyczkę GStreamer dla biblioteki ALSA. ALSA to Advanced Linux Sound Architecture.";
dict.entries['media']['gstreamerlibav'] = "Ta wtyczka GStreamer obsługuje dużą liczbę formatów kompresji audio i wideo dzięki wykorzystaniu biblioteki libav. Wtyczka zawiera elementy GStreamer do kodowania ponad 40 formatów (MPEG, DivX, MPEG4, AC3, DV, ...), dekodowanie ponad 90 formatów (AVI, MPEG, OGG, Matroska, ASF, ...), demuxowanie ponad 30 formatów.";
dict.entries['media']['gstreamerpluginsbad'] = "Wtyczki GStreamera z zestawu bad odstają jakością od pozostałych. Często są blisko osiągnięcia dobrej jakości, ale czegoś im brakuje - może to być dobry przegląd kodu, dokumentacja, zestaw testów, aktywny opiekun lub faktyczne, szersze zastosowanie.";
dict.entries['media']['gstreamerpluginsbase'] = "Ten pakiet zawiera wtyczki GStreamer z zestawu 'base'. Stanowi on zestaw niezbędnych wtyczek.";
dict.entries['media']['gstreamerpluginsgood'] = "Ten pakiet zawiera wtyczki GStreamer z zestawu 'good'. Stanowi on zestaw wtyczek dobrej jakości na licencji LGPL.";
dict.entries['media']['gstreamerpluginsugly'] = "Pakiet zawiera wtyczki GStreamer z zestawu 'ugly'. Stanowi on zestaw wtyczek dobrej jakości, których rozpowszechnianie może być ryzykowne ze względu na problemy z patentami.";
dict.entries['media']['gstreamerpulseaudio'] = "Pakiet zawiera wtyczki GStreamer do PulseAudio, serwera dźwięku dla systemów POSIX i Win32.";
dict.entries['media']['lame'] = "LAME (rekurencyjny skrót od LAME Is not a MP3 Encoder) to projekt badawczy, którego celem jest poznanie i udoskonalenie technologii kodowania MP3. LAME zawiera bibliotekę kodowania MP3, prostą aplikację frontendową i inne narzędzia do analizy dźwięku, a także wygodne narzędzia.";
dict.entries['media']['libdvdpkg'] = "Ten pakiet zawiera biblioteki potrzebne do odtwarzania płyt wideo DVD odtwarzaczem multimediów (takich jak VLC, SMplayer, Totem itp.). Automatyzuje proces pobierania plików źródłowych, ich kompilacji i instalowania pakietów binarnych.";
dict.entries['media']['libdvdread4'] = " Biblioteka libdvdread zawiera funkcje, które pozwalają uzyskać dostęp do wielu płyt DVD. Przetwarza pliki IFO, odczytuje bloki NAV oraz realizuje uwierzytelnianie i dekodowanie CSS.";
dict.entries['media']['mencoder'] = "Pakiet zawiera menconder, prosty koder zaprojektowany do transkodowania filmów, które mogą być odtwarzane przez program MPlayer (AVI / ASF / OGG / DVD / VCD / VOB / MPG / MOV / VIV / FLI / RM / NUV / NET), do innych formatów przez niego obsługiwanych. Może korzystać z różnych kodeków, takich jak: DivX4 (1 lub 2 przejścia), libavcodec oraz audio PCM/MP3/ VBRMP3. Umożliwia również kopiowanie filmów wideo i zmianę rozmiaru strumieni.";
dict.entries['media']['mkvtoolnix'] = "Matroska to format multimedialnego kontenera, bazujący na EBML-u (Extensible Binary Meta Language), który jest rodzajem binarnego XML-a. Poniższe narzędzia pozwalają zarządzać plikami Matroska.";
dict.entries['media']['mpg123'] = "mpg123 jest pracującym w czasie rzeczywistym odtwarzaczem audio/dekoderem do 1, 2 i 3 warstwy formatu MPEG 1.0/2.0/2.5 (warstwa 3 formatu MPEG 1.0 znana jest także jako MP3). Pakiet zawiera wtyczki wyjściowe do kilku systemów audio, w tym: OSS4, Advanced Linux Sound Architecture (ALSA), JACK, PortAudio, PulseAudio, OpenAL i Network Audio System (NAS).";
dict.entries['media']['ogmtools'] = "Narzędzia do manipulowania strumieniami multimedialnymi Ogg.";
dict.entries['media']['twolame'] = "TwoLAME to zoptymalizowany koder MPEG Audio Layer 2. Bazuje na LAME od Mike'a Chenga, który z kolei oparty jest na kodzie ISO dist10 i częściach LAME. Ze względu na problemy patentowe związane z koderami MPEG Audio Layer 3 (MP3), zdolność większości odtwarzaczy MPEG Audio do odtwarzania plików warstwy 2 oraz podobieństwo składni wiersza poleceń i interfejsu API, TwoLAME stanowi bardzo dobry zamiennik dla LAME lub inne enkodery warstwy 3.";
dict.entries['media']['vorbistools'] = "vorbis-tools zawierają: oggenc (koder), ogg123 (narzędzie odtwarzania), ogginfo (wyświetla informacje ogg), oggdec (dekoduje pliki ogg), vcut (narzędzie do dzielenia plików ogg) i vorbiscomment (edytor komentarza ogg).";
dict.entries['media']['x264'] = "x264 to zaawansowany koder działający z linii poleceń do tworzenia strumieni wideo H.264 (MPEG-4 AVC).";
dict.entries['media']['x265'] = "x265 to koder działający z linii poleceń do tworzenia strumieni wideo H.265 / High Efficiency Video Coding (HEVC).";
// multimedia others
dict.entries['media']['gtkrecordmydesktop'] = "Graficzny interfejs do recordMyDesktop, narzędzia wykonującego zrzuty ekranu. Dodaje łatwą w obsłudze graficzną ikonę na pasku narzędzi GNOME do wykonywania zrzutów ekranu za pomocą aplikacji przechwytującej audio i wideo recordMydesktop.";
dict.entries['media']['kazam'] = "Kazam zapewnia dobrze zaprojektowany i łatwy w użyciu interfejs do przechwytywania screencastów i zrzutów ekranu. Może nagrywać wideo na pulpicie i wiele strumieni audio jednocześnie z kontrolą poziomów audio i przechwytywaniem regionu ekranu.";
dict.entries['media']['kover'] = "Kover to program WYSIWYG służący do drukowania okładek CD. Masz możliwość wpisania tytułu, zawartości, ustawienia kolorów tła, wprowadzenia tekstu, osadzenia obrazów lub przesłania tytułu i ścieżek z CDDB (w tym CDDB Code 211). Kover może uwierzytelniać za pośrednictwem serwera proxy (Basic, ale nie Digest) w celu uzyskania dostępu do CDDB i tworzyć żądanie CDDB po prostu wprowadzając identyfikator CDDB (tzn. Nie trzeba wkładać płyty CD).";
dict.entries['media']['lxmms2'] = "lxmms2 to mały klient XMMS2 do sterowania XMMS2 za pomocą pilota zdalnego sterowania LIRC.";
dict.entries['media']['vokoscreen'] = "vokoscreen może być używany do nagrywania filmów edukacyjnych, nagrań na żywo przeglądarki, instalacji, wideokonferencji itp. Możesz nagrać sam film lub wideo i dźwięk (za pomocą ALSA lub PulseAudio).";
// multimedia subtitles
dict.entries['media']['gnomesubtitles'] = "GNOME Subtitles jest edytorem napisów do środowiska GNOME. Obsługuje najpopularniejsze tekstowe formaty napisów, podgląd wideo, synchronizację wybranych scen i tłumaczenie napisów. Niektóre z obsługiwanych formatów napisów to: Advanced Sub Station Alpha, FAB Subtitler, MicroDVD, MPlayer 1/2, MPSub, SubRip i SubViewer 1/2.";
dict.entries['media']['subtitlecomposer'] = "Edytor napisów działający w trybie tekstowym, obsługujący podstawowe operacje (edycja tekstu, czasu i stylu), podgląd w czasie rzeczywistym i sprawdzanie pisowni. Inne wymyślne funkcje, np. opóźniają wszystkie napisy w bieżącym pliku napisów, sprawdzając błędy lub tworzą tłumaczenia. Różne backendy (GStreamer, MPlayer, MPV lub Phonon) mogą być używane do odtwarzania podglądu wideo w czasie rzeczywistym, co pomaga zsynchronizować napisy.";
dict.entries['media']['subtitleeditor'] = "Subtitle Editor jest opartym na GTK+2 narzędziem do edycji napisów. Może być użyty do tworzenia nowych napisów lub jako narzędzie do przekształcania, edycji, korekty i udoskonalania już istniejących. Program pokazuje także ścieżkę dźwiękową, co sprawia, że łatwiej jest synchronizować napisy z dialogami.";'
// multimedia video editors
dict.entries['media']['avidemux'] = "Avidemux to darmowy edytor wideo przeznaczony do prostych zadań związanych z cięciem, filtrowaniem i kodowaniem. Obsługuje wiele typów plików, w tym pliki MPEG zgodne z AVI, DVD, MP4 i ASF, używając różnych kodeków. Zadania można zautomatyzować za pomocą projektów, kolejki zadań i zaawansowanych funkcji skryptowania.";
dict.entries['media']['blender'] = "Blender jest zintegrowanym pakietem narzędziowym służącym do trójwymiarowego modelowania, animacji, renderingu, postprodukcji, interaktywnego tworzenia i odtwarzania (gier). Blender dysponuje własnym, wyjątkowym interfejsem użytkownika, stworzonym w całości w oparciu o OpenGL i zaprojektowanym z myślą o szybkości. Wiązania Pythona dostępne są do obsługi skryptów; funkcje importu/eksportu popularnych formatów plików jak 3D Studio i Wavefront OBJ zostały zaimplementowane przez społeczność jako skrypty. Fotosy, animacje, modele dla gier, silniki spoza projektu oraz interaktywne treści w postaci niezależnych plików binarnych są powszechnymi produktami używania Blendera.";
dict.entries['media']['dvd95'] = "DVD95 to aplikacja GNOME służąca do konwertowania plików DVD9 na DVD5 (4.7 GB), AVI lub PSP. Interfejs użytkownika jest prosty i elegancki w użyciu.";
dict.entries['media']['devede'] = "DeVeDe to program służący do tworzenia filmów DVD, nadających się do uruchamiania na odtwarzaczach domowych, z dowolnej ilości plików wideo, w dowolnym formacie obsługiwanym przez program Mplayer. Pozwala on użytkownikowi na tworzenie napisów a nawet menu.";
dict.entries['media']['dvdstyler'] = "DVDStyler to wieloplatformowa darmowa aplikacja do tworzenia profesjonalnie wyglądających płyt DVD. Pozwala nie tylko na nagrywanie plików wideo na DVD, które można odtwarzać praktycznie na każdym samodzielnym odtwarzaczu DVD, ale także na tworzenie indywidualnie zaprojektowanych menu DVD.";
dict.entries['media']['flowblade'] = "Edytor filmów Flowblade zapewnia szybką, precyzyjną i jak najprostszą możliwą edycję. Flowblade stosuje paradygmat edytowania stylu filmowego, w którym klipy są zwykle automatycznie umieszczane ciasno po poprzednim klipie - lub między dwoma istniejącymi klipami - kiedy są wstawiane na osi czasu. Zmiany są dostrajane poprzez przycinanie i wycinanie punktów klipów lub przez wycinanie i usuwanie części klipów. Edycja stylu filmowania jest szybsza w przypadku tworzenia programów, głównie prostych cięć i dzieleń audio, ale może być wolniejsza, gdy programy zawierają skomplikowane kompozyty, o ile nie jest przestrzegany prawidłowy przepływ pracy.";
dict.entries['media']['kdenlive'] = "Kdenlive jest nieliniowym pakietem oprogramowania do edycji wideo, obsługującym DV, HDC i wiele innych formatów. Oto jego najważniejsze cechy: przewodnik i znacznik do organizowania osi czasu; obsługa kopiowania i wklejania wideoklipów, efektów i przejść; zmiany w czasie rzeczywistym; przechwytywanie z Firewire i Video4Linux; przechwytywanie zawartości ekranu; eksport do dowolnego formatu obsługiwanego przez FFMPEG.";
dict.entries['media']['lives'] = "LiVES to system edycji wideo pozwalający zarówno początkującym, jak i zaawansowanym użytkownikom na natychmiastową edycję i tworzenia wideo. Może być również wykorzystywany jako narzędzie VJ, oraz oskryptowanym i zdalnie sterowanym systemem.";
dict.entries['media']['ogmrip'] = "OGMRip to aplikacja i zestaw bibliotek do zgrywania i kodowania DVD do plików AVI, OGM MP4 lub Matroska przy użyciu szerokiej gamy kodeków. Do wykonania swoich zadań używa mplayer, mencoder, ogmtools, mkvtoolnix, oggenc, lame i faac.";
dict.entries['media']['openshot'] = "OpenShot Video Editor jest darmowym, otwartoźródłowym, nieliniowym edytorem wideo. Służy do tworzenia i edytowania wideo oraz innych filmów używając wielu formatów dźwiękowych, filmowych i graficznych. Umożliwia tworzenie filmów do YouTube, Flickr, Vimeo, Metacafe, iPoda, Xboksa oraz w wielu innych popularnych formatach.";
dict.entries['media']['qstopmotion'] = "Użytkownicy będą mogli tworzyć animacje ze zdjęć zaimportowanych z kamery lub dysku twardego i eksportować animację do różnych formatów wideo, takich jak mpeg lub avi. qStopMotion jest forkiem Stopmotion dla systemu Linux.";
dict.entries['media']['shotcut'] = "Darmowa i wieloplatformowa aplikacja do edycji wideo. Shotcut obsługuje wiele formatów wideo, audio i obrazów za pośrednictwem FFmpeg i przechwytywanie ekranu i dźwięku oraz obrazu z kamery internetowej. Wykorzystuje oś czasu do nieliniowej edycji wideo wielu ścieżek, które mogą składać się z różnych formatów.";
dict.entries['media']['stopmotion'] = "Twórz animacje poklatkowe ze zdjęciami pobranymi z urządzenia wideo lub z plików graficznych lub ze zdjęć wyodrębnionych z wideo. Stopmotion ma zestaw narzędzi, które pomagają utrzymać ruchy płynne i precyzyjne, takie jak wyświetlanie ostatniego obrazu na żywo z następnego obrazu.";
dict.entries['media']['winff'] = "WinFF jest graficznym interfejsem użytkownika do FFmpeg lub avconv. Jest w stanie konwertować prawie każdy plik wideo, który może być konwertowany przez FFmpeg lub avconv. WinFF może działać na wielu plikach i formatach jednocześnie. Może np. wykonać konwersję mpeg, flv i mov na avi (lub format AVI/DVD, MPEG, 3gp, itp.), i to wszystko na raz.";
dict.entries['media']['xjadeo'] = "Prosty odtwarzacz wideo, który otrzymuje synchronizację z jackd lub MTC. Posiada aplikacje do tworzenia ścieżek dźwiękowych, monitoringu wideo lub dowolnego zadania, które wymaga skojarzenia klatek filmowych ze zdarzeniami dźwiękowymi.";
// multimedia video players
dict.entries['media']['gnomempv'] = "GNOME MPV to prosty frontend GTK + dla mpv. GNOME MPV współdziała z mpv poprzez interfejs API klienta wyeksportowany przez libmpv, umożliwiając dostęp do potężnych możliwości odtwarzania MPV.";
dict.entries['media']['kmplayer'] = "MPlayer to darmowy i rozbudowany odtwarzacz multimedialny. Obsługuje wszystkie najpopularniejsze formaty audio i wideo (m.in. AVI, MP4, MPEG1, MPEG2, MPEG4, MOV, RMVB, WMV, MP3, OGG i WMA) oraz bez problemów odtwarza płyty DVD-Video i Blu-ray.";
dict.entries['media']['kodi'] = "Kodi, wcześniej znany jako XBMC, to nagradzany, darmowy i otwarty program do odtwarzania multimediów i centrum rozrywki dla wszystkich multimediów cyfrowych. Obsługuje niemal nieskończoną gamę pilotów zdalnego sterowania a w połączeniu z pięknym interfejsem i mocnym silnikiem do modelowania skóry, Kodi wydaje się być bardzo naturalny w użyciu z kanapy i jest idealnym rozwiązaniem do kina domowego.";
dict.entries['media']['motionbox'] = "MotionBox to przeglądarka wideo dla Motion Freedom. Zbudowany do uzyskiwania dostępu i przechodzenia między zdecentralizowanymi źródłami wideo. Zbudowany do ładowania i odtwarzania wielu zasobów wideo.";
dict.entries['media']['mplayer'] = "MPlayer odtwarza większość plików w formatach: MPEG, VOB, AVI, Ogg/OGM, VIVO, ASF/WMA/WMV, QT/MOV/MP4, FLI, RM, NuppelVideo, yuv4mpeg, FILM, RoQ, PVA, obsługiwanych przez wiele natywnych kodeków: XAnim, RealPlayer i Win32 DLL. Może także odtwarzać filmy VideoCD, SVCD, DVD, 3ivx, RealMedia i DivX.";
dict.entries['media']['mpv'] = "mpv to odtwarzacz filmów oparty na MPlayerze i mplayer2. Obsługuje szeroką gamę formatów plików wideo, kodeki audio i wideo oraz różne typy napisów.";
dict.entries['media']['parole'] = "Parole jest odtwarzaczem multimedialnym do środowiska Xfce, napisany przy uzyciu frameworka GStreamer. Parole posiada funkcje odtwarzania plików lokalnych mediów, w tym wideo z obsługą napisów, DVD/CD i transmisje na żywo; jest także rozszerzalny za pomocą wtyczek.";
dict.entries['media']['rage'] = "Odtwarzacz wideo dla Enlightenment.";
dict.entries['media']['smplayer'] = "Graficzna nakładka bazująca na Qt5 dla mplayera i jego modyfikacji, z podstawowymi funkcjami takimi jak odtwarzanie filmów, DVD i VCD, do bardziej zaawansowanych funkcji, takich jak obsługa filtrów MPlayera i wiele innych. Jedna z najciekawszych funkcji SMPlayera: zapamiętuje ustawienia wszystkich plików, które odtwarzasz.";
dict.entries['media']['smtube'] = "SMTube to samodzielna aplikacja graficzna, która umożliwia wyszukiwanie i pobieranie filmów z YouTube. Chociaż jest częścią projektu SMPlayer, może być używany z dowolnym odtwarzaczem multimedialnym, takim jak MPlayer, MPlayer2, VLC, Totem lub Gnome-MPlayer.";
dict.entries['media']['totem'] = "Totem jest prostym, a zarazem funkcjonalnym odtwarzaczem multimedialnym do środowiska graficznego GNOME, umożliwiającym odczytywanie wielu formatów plików.";
dict.entries['media']['vlc'] = "VLC jest odtwarzaczem multimediów projektu VideoLAN. Odtwarza pliki MPEG, MPEG-2, MPEG-4, DivX, MOV, WMV, QuickTime, WebM, FLAC, MP3, Ogg / Vorbis, DVD, VCD, podcasty i strumienie multimedialne z różnych źródeł sieciowych. VLC może być również wykorzystywany jako serwer streamingowy, który duplikuje strumień, który odczytuje i przesyła je przez sieć do innych klientów lub obsługuje je za pośrednictwem protokołu HTTP.";
dict.entries['media']['xineconsole'] = "Odtwarzacz wideo xine, interfejs użytkownika. Ten pakiet zawiera dodatkowe nakładki, aaxine, cacaxine i fbxine, które działają nawet w konsoli, więc możesz oglądać swoje DVD nawet w xterm.";
dict.entries['media']['xineui'] = "Odtwarzacz wideo xine, graficzny interfejs użytkownika, bazujący na X11 dla biblioteki odtwarzacza wideo libxine. Dostarcza xine, używającego skórek odtwarzacza multimedialnego, który potrafi odtwarzać wszystkie formaty audio/wideo obsługiwane przez libxine. Obecnie obejmuje to MPEG1/2, pliki AVI i Quicktime, niektóre metody strumieniowania sieciowego i inne media bazujące na płytach (VCD, SVCD, DVD).";
