// Polish localization file for Graphics
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2019/12/30 by pavroo
dict.entries['graphics'] = {};
// graphics editors
dict.entries['graphics']['blender'] = "Blender jest zintegrowanym pakietem narzędziowym służącym do trójwymiarowego modelowania, animacji, renderingu, postprodukcji, interaktywnego tworzenia i odtwarzania (gier). Blender dysponuje własnym, wyjątkowym interfejsem użytkownika, stworzonym w całości w oparciu o OpenGL i zaprojektowanym z myślą o szybkości.";
dict.entries['graphics']['darktable'] = "Darktable zarządza cyfrowymi negatywami użytkownika w bazie danych, pozwalając na oglądanie ich przez powiększający stół podświetlany. Umożliwia również obróbkę plików w formacie surowym (RAW). Program wypełnienia lukę pomiędzy wieloma istniejącymi, wolnymi i znakomitymi konwerterami RAW oraz narzędziami do zarządzania obrazami (takimi jak UFRraw lub F-Spot). Interfejs użytkownika jest budowany w oparciu o wydajne buforowanie metadanych obrazu oraz wszystkie przechowywane w bazie danych mip-mapy. Użytkownik zawsze może pracować z obrazem, nawet jeśli obraz nie został załadowany do pełnej rozdzielczości.";
dict.entries['graphics']['fotoxx'] = "Fotoxx jest programem do poprawiania zdjęć cyfrowych. Umożliwia poruszanie się po dużych katalogach ze zdjęciami za pomocą okna miniatur, tworzenie obrazów HDR (High Dynamic Range) dzięki połączeniu obrazów jasnych jak i ciemnych w celu poprawy szczegółów widocznych zarówno w obszarach jasnych jak i ciemnych, tworzenie panoram z połączenia pokrywających się obrazów, ustawianie jasności i intensywności kolorów niezależnie od różnych, istniejących poziomów jasności, redukcję mgły lub zamglenia poprzez usunięcie bieli i intensyfikację kolorów, obracanie obrazu (stopniowe przechylanie obrazu lub obrót o 90 stopni), usuwanie efektu czerwonych oczu z elektronicznych zdjęć wykonanych z lampą błyskową, wyostrzanie, zmianę rozmiaru lub kadrowanie, redukcję szumów przy słabym naświetleniu zdjęcia, zmianę głębi kolorów oraz rozciąganie obrazu poprzez przeciąganie go za pomocą myszki.";
dict.entries['graphics']['gimp'] = "GIMP jest zaawansowanym edytorem obrazów. Można go używać do edytowania, poprawiania oraz retuszowania zdjęć i skanów, tworzenia rysunków oraz własnych obrazów. Udostępnia dużą kolekcję profesjonalnych narzędzi edycyjnych i filtrów, podobnych do tych, które można znaleźć w programie Photoshop. Oferuje wiele ustawień oraz funkcji zapewniających pełną kontrolę nad obrazami, w tym warstwy, ścieżki, maski oraz skrypty. Obsługiwanych jest wiele formatów plików graficznych m.in. pliki JPEG, pliki programów Photoshop (.psd) i Paint Shop Pro (.psp). GIMP może być również używany do skanowania i drukowania zdjęć.";
dict.entries['graphics']['gnomepaint'] = "Gnome-paint to program zainspirowany przez MS Paint i zaprojektowany dla środowiska graficznego GNOME (i może innych). Może być używany do manipulowania obrazami w bardzo prosty sposób. Wraz z bardzo przyjaznym interfejsem gnome-paint jest łatwy w obsłudze dla początkujących użytkowników.";
dict.entries['graphics']['hugin'] = "Hugin jest programem do łączenia zdjęć w panoramę. W gruncie rzeczy, Hugin jest graficznym interfejsem użytkownika do Panorama Tools. Łączenie kilku zachodzących na siebie zdjęć, zrobionych z tego samego miejsca, w jeden większy obraz jest realizowane poprzez ich przekształcanie i wyrównywanie do utworzonych punktów kontrolnych. Hugin umożliwia łatwe tworzenie punktów kontrolnych pomiędzy dwoma zdjęciami, optymalizację przekształcania grafik itd.";
dict.entries['graphics']['imagemagick'] = "ImageMagick to pakiet oprogramowania do tworzenia i edytowania obrazów bitmapowych. Może czytać, konwertować i zapisywać obrazy w różnych formatach (ponad 100), w tym DPX, EXR, GIF, JPEG, JPEG-2000, PDF, PhotoCD, PNG, Postscript, SVG i TIFF. Użyj ImageMagick, aby tłumaczyć, obracać, odbijać, skalować, ścinać i przekształcać obrazy, dostosowywać kolory obrazu, stosować różne efekty specjalne lub rysować tekst, linie, wielokąty, elipsy i krzywe Béziera.";
dict.entries['graphics']['inkscape'] = "Inkscape jest edytorem ilustracji, posiadającym wszystko, co jest potrzebne do tworzenia profesjonalnej grafiki komputerowej. Można go używać do tworzenia diagramów, ilustracji, rysunków technicznych, grafiki internetowej, ikon i logo. Zbiór praktycznych samouczków pokazuje jak połączyć w jeden obraz linie, figury oraz różne rodzaje i style tekstu.";
dict.entries['graphics']['k3d'] = "K-3D to darmowe oprogramowanie do modelowania i animacji 3D. Łączy elastyczne wtyczki z wizualizacyjną architekturą programu, czyniąc z K-3D wszechstronne i potężne narzędzie dla artystów.";
dict.entries['graphics']['karbon'] = "Karbon jest aplikacją do tworzenia grafiki wektorowej, zawierającą prosty, wysoce konfigurowalny i rozszerzalny interfejs użytkownika. Czyni to z niego znakomitą aplikację dla użytkowników zaczynających odkrywać świat grafiki wektorowej, jak również dla artystów, którzy chcą tworzyć zapierającą dech w piersiach grafikę wektorową.";
dict.entries['graphics']['kolourpaint4'] = "KolourPaint jest prostą aplikacją do rysowania i edytowania obrazów w środowisku KDE. Jest łatwy w użyciu, zapewniając poziom funkcjonalności ukierunkowany na przeciętnego użytkownika. Stanowi idealne rozwiązanie do wykonywania typowych zadań, takich jak rysowanie prostej grafiki i retuszowanie zdjęć.";
dict.entries['graphics']['krita'] = "Krita to kreatywna aplikacja do obrazów rastrowych. Niezależnie od tego, czy chcesz tworzyć od podstaw, czy pracować z istniejącymi obrazami, Krita jest dla Ciebie. Możesz pracować ze zdjęciami lub zeskanowanymi obrazami lub zacząć od pustej planszy. Krita obsługuje większość kart graficznych zaraz po instalacji.";
dict.entries['graphics']['lightzone'] = "LightZone to profesjonalne, otwarto-źródłowe, cyfrowe oprogramowanie ciemni dla systemów Windows, Mac OS X i Linux. Zamiast używania warstw, jak wiele innych edytorów zdjęć, LightZone pozwala użytkownikowi zbudować stos narzędzi, które można przestawiać, wyłączać i włączać oraz usuwać ze stosu. Jest to nieniszczący edytor, w którym dowolne z narzędzi można później zmienić lub zmodyfikować - nawet w innej sesji edycyjnej.";
dict.entries['graphics']['opentoonz'] = "Oprogramowanie do tworzenia animacji 2D o otwartym kodzie źródłowym. Oparty jest na oprogramowaniu Toonz, opracowanym przez firmę Digital Video S.p.A we Włoszech, dostosowanym przez Studio Ghibli i był używany do tworzenia jego dzieł przez wiele lat. Dwango uruchamiło projekt OpenToonz we współpracy z Digital Video i Studio Ghibli.";
dict.entries['graphics']['rawtherapee'] = "RawTherapee to zaawansowany program do przetwarzania surowych zdjęć i edytowania zdjęć niesurowych. Jest nieniszczący, korzysta z OpenMP, obsługuje wszystkie kamery obsługiwane przez dcraw i wykonuje swoje obliczenia w wysoce precyzyjnym 32-bitowym silniku zmiennoprzecinkowym. RawTherapee obsługuje JPEG, PNG i TIFF jako format wyjściowy dla przetworzonych zdjęć.";
dict.entries['graphics']['synfigstudio'] = "Synfig to wektorowy pakiet animacji 2D. Został zaprojektowany, aby umożliwić tworzenie animacji o jakości filmu fabularnego. Eliminuje to potrzebę tworzenia klatek pośrednich, zapobiegając konieczności ręcznego rysowania każdej klatki.";
dict.entries['graphics']['tuxpaint'] = "Tux Paint powstał jako prosty program do rysowania dla małych dzieci. Z założenia nie jest to narzędzie graficzne ogólnego przeznaczenia. Program ma być zabawny i łatwy do używania. Efekty dźwiękowe i postać Tuxa pomagają użytkownikowi zorientować się, co się dzieje i zabawiają go.";
dict.entries['graphics']['xpaint'] = "XPaint jest programem do tworzenia prostych grafik. Posiada kilka zaawansowanych funkcji, między innymi do przetwarzania obrazu czy wypełniania gradientem.";
// graphics others
dict.entries['graphics']['camorama'] = "Camorama to małe narzędzie do przeglądania i zapisywania obrazów z kamery internetowej lub jakiegokolwiek urządzenia Video4Linux. Potrafi stosować szereg filtrów i dokonywać zdalnego przechwycenia.";
dict.entries['graphics']['gtkam'] = "GTKam to graficzna aplikacja oparta na GTK+ umożliwiająca pobieranie obrazów i filmów z aparatów cyfrowych.";
dict.entries['graphics']['kamera'] = "Obsługa aparatów cyfrowych do aplikacji KDE. Pakiet pozwala aplikacjom KDE na dostęp i manipulację obrazami w aparatach cyfrowych.";
dict.entries['graphics']['qcamera'] = "Prosta i mała, bazująca na Qt aplikacja do obsługi  kamery internetowej.";
// graphics screenshots
dict.entries['graphics']['flameshot'] = "Flameshot to potężne, ale proste w obsłudze oprogramowanie do zrzutu ekranu. Godne uwagi funkcje to konfigurowalny wygląd, edycja zrzutu ekranu w aplikacji, interfejs D-Bus, eksperymentalna obsługa GNOME / KDE Wayland, integracja z Imgur oraz obsługa interfejsu GUI i CLI.";
dict.entries['graphics']['gnomescreenshot'] = "Aplikacja do GNOME robiąca zrzuty ekranu. Narzędzie pobierające obraz pulpitu lub okna i zapisujące go do pliku.";
dict.entries['graphics']['gscreenshot'] = "Interfejs graficzny oparty na Python-ie dla narzędzia Scrot, który pozwala wykonać zrzut ekranu pulpitu.";
dict.entries['graphics']['kdespectacle'] = "Narzędzie do przechwytywania zrzutów ekranu, zastępuje KSnapshot. Spectacle rejestruje obrazy ekranu, może przechwycić cały ekran, określony region, pojedyncze okno lub tylko część okna.";
dict.entries['graphics']['screengrab'] = "Wieloplatformowe narzędzie do uzyskiwania zrzutów ekranu. Screengrab działa w systemach Linux i Windows. Program używa Qt i jest niezależny od środowiska graficznego.";
dict.entries['graphics']['screenieqt'] = "Screenie to małe narzędzie, które pozwala komponować fantazyjne i stylowe zrzuty ekranu. Jest to aplikacja wieloplatformowa (dla systemów Linux, Windows i Mac OS X) i bardzo łatwa w użyciu. Będziesz miał imponujący zrzut ekranu w ciągu zaledwie minuty!";
// graphics viewers
dict.entries['graphics']['digikam'] = "Program do zarządzania zdjęciami cyfrowymi przeznaczony do importowania, organizowania, ulepszania, wyszukiwania i eksportowania obrazów cyfrowych do i z komputera. Zapewnia prosty interfejs, który sprawia, że importowanie i organizowanie cyfrowych zdjęć jest szybkie. digiKam umożliwia zarządzanie dużą liczbą zdjęć cyfrowych w albumach i porządkowanie tych zdjęć w celu łatwego wyszukiwania za pomocą tagów (słów kluczowych), podpisów, kolekcji, dat, geolokalizacji i wyszukiwań. Ma wiele funkcji do przeglądania, organizowania, przetwarzania i udostępniania zdjęć. W ten sposób digiKam jest potężnym oprogramowaniem do zarządzania zasobami cyfrowymi (DAM), w tym zaawansowanymi funkcjami edycji obrazu.";
dict.entries['graphics']['eog'] = "EoG lub Eye of GNOME jest prostą przeglądarką grafiki dla pulpitu GNOME, która używa bibliotekę gdk-pixbuf. Obsługuje duże obrazy, a także powiększanie i przewijanie obrazów przy stałym użyciu pamięci. Jego cele to prostota oraz zgodność ze standardami.";
dict.entries['graphics']['eom'] = "EoM lub Eye of MATE jest prostą przeglądarką grafiki dla pulpitu MATE, która używa bibliotekę gdk-pixbuf. Obsługuje duże obrazy, a także powiększanie i przewijanie obrazów przy stałym użyciu pamięci. Jego cele to prostota oraz zgodność ze standardami.";
dict.entries['graphics']['ephoto'] = "Wszechstronna przeglądarka obrazów napisana przy użyciu języka EFL.";
dict.entries['graphics']['feh'] = "Feh jest szybką i lekką przeglądarką plików graficznych, opartą na bibliotece graficznej imlib2. Sterowana z wiersza poleceń obsługuje wiele obrazów poprzez wyświetlanie slajdów, przeglądanie miniatur lub wielu okien, tworzenie kolaży z wielu zdjęć i drukowanie indeksu (używając czcionek TrueType do wyświetlania informacji o pliku).";
dict.entries['graphics']['geeqie'] = "Przeglądarka obrazów Geeqie oferuje możliwość otwierania plików graficznych przy użyciu pojedynczego kliknięcia. Program pozwala na przeglądanie miniaturek, powiększanie, filtrowanie i obsługę zewnętrznego edytora.";
dict.entries['graphics']['gpicview'] = "GPicView jest lekką przeglądarką opartą o bibliotekę GTK+ 2.x, posiadającą następujące cechy: ekstremalna lekkość i szybkość, połączona z niskim zużyciem pamięci, odpowiednia jako domyślna przeglądarka obrazów dla środowiska graficznego, prosty i intuicyjny interfejs, etc.";
dict.entries['graphics']['gthumb'] = "Program gThumb jest zaawansowaną przeglądarką obrazów. Posiada wiele użytecznych funkcji, służących do: przeglądania systemu plików, pokazywania slajdów, obsługiwania katalogów zdjęciowych, tworzenia albumów internetowych, importowania obrazów z aparatów fotograficznych, nagrywania obrazów na CD, wsadowych operacji plikowych. Ponadto udostępnia funkcje do szybkiego edytowania obrazów, takie jak: transformacje i manipulacje kolorami.";
dict.entries['graphics']['gwenview'] = "Gwenview jest przeglądarką obrazów, idealną do przeglądania i wyświetlania kolekcji grafik. Jest zdolna do pokazywania obrazów jako pełnoekranowych pokazów slajdów i dokonywania prostych poprawek np. obracania lub przycinania grafik.";
dict.entries['graphics']['lximageqt'] = "Prosta przeglądarka obrazów dla LXQt. Dodatkowe formaty plików można dodać, jeśli zainstalujesz wtyczki qt5-image-formats-plugins.";
dict.entries['graphics']['ristretto'] = "Lekka przeglądarka obrazów dla środowiska graficznego Xfce.";
dict.entries['graphics']['shotwell'] = "Shotwell jest organizerem cyfrowych fotografii, zaprojektowanym do środowiska GNOME. Umożliwia importowanie zdjęć z dysku lub kamery, organizowanie ich na różne sposoby, wyświetlanie w pełnym oknie lub trybie pełnoekranowym oraz eksportowanie ich w celu dzielenia się z innymi. Jest w stanie zarządzać wieloma różnymi formatami graficznymi, w tym także surowymi plikami CR2.";
dict.entries['graphics']['viewnior'] = "To jest Viewnior, program do przeglądania obrazów. Stworzony, by być prosty, szybki i elegancki. Jego minimalistyczny interfejs zapewnia więcej przestrzeni ekranu dla obrazów.";
dict.entries['graphics']['xnview'] = "XnView to organizer obrazów i uniwersalny menedżer plików służący do przeglądania, konwertowania, organizowania i edycji obrazów rastrowych, a także ogólnego zarządzania plikami. Jest wyposażony we wbudowaną kontrolę heksadecymalną, zmianę nazw partii i narzędzia do przechwytywania ekranu. Jest licencjonowany jako darmowy dla użytkowania prywatnego, edukacyjnego i non-profit. W przypadku innych zastosowań jest licencjonowany jako oprogramowanie komercyjne.";
