// Fichier de localisation française de Web
// Copyright 2016 hiver <hiver@club-internet.fr>
// Copyright 2018 Jean-Albert Caire
// Sous licence GNU GPL v2
// last update 2018/12/12 by pavroo
dict.entries['web'] = {};
// web communication
dict.entries['web']['bti'] = "bti sends a tweet message to twitter.com. bti provides an easy way to send tweet messages directly from the command line or a script. It reads the message on standard input and uses the account and password settings either from the command line options or from a config file to deliver the message.";
dict.entries['web']['caprine'] = "Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features.";
dict.entries['web']['corebird'] = "Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It features inline image and video preview, creation of lists and favorites, filtering of tweets and full text search. Corebird is able to manage multiple Twitter accounts.";
dict.entries['web']['discord'] = "Discord is a freeware VoIP application and digital distribution platform designed for video gaming communities, that specializes in text, image, video and audio communication between users in a chat channel.";
dict.entries['web']['ekg2'] = "EKG2 is an open source instant messenger program for UNIX systems. The program has a plugin-based structure, and supports multiple protocols, currently Jabber, ICQ, Gadu-Gadu, IRC, RivChat, PolChat, NNTP and RSS. "
dict.entries['web']['empathy'] = "Instant messaging program supporting text, voice, video, file transfers and inter-application communication over many different protocols, including: AIM, Windows Live (MSN), Google Talk (Jabber/XMPP), Yahoo!, Salut, Gadu-Gadu, Groupwise and ICQ.";
dict.entries['web']['gajim'] = "Gajim is a Jabber client. It has a tabbed user interface with normal chats, group chats, and has many features such as, TLS, GPG, SSL, multiple accounts, avatars, file transfers, audio/video call, D-Bus and Metacontacts.";
dict.entries['web']['hexchat'] = "HexChat is a graphical IRC client with a GTK+ GUI. Features include Python and Perl scripting support, a plugin API, multiple server/channel windows, spell checking, multiple authentication methods including SASL, and customizable notifications.";
dict.entries['web']['ircii'] = "The ircII program is a full screen, termcap based interface to Internet Relay Chat. It gives full access to all of the normal IRC functions, plus a variety of additional options. This Version is able to display mIRC colors.";
dict.entries['web']['irssi'] = "Irssi is a terminal based IRC client for UNIX systems. It also supports SILC and ICB protocols via plugins.";
dict.entries['web']['kadu'] = "Gadu-Gadu is a Windows instant messenger, very popular in Poland. Kadu is a Qt5 client of Gadu-Gadu and XMPP for *nix systems. This package provides Kadu along with plugins developed by Kadu developers.";
dict.entries['web']['konversation'] = "Konversation is a client for the Internet Relay Chat (IRC) protocol. It is easy to use and well-suited for novice IRC users, but novice and experienced users alike will appreciate its many features.";
dict.entries['web']['kopete'] = "Kopete is an instant messaging and chat application with support for a wide variety of services, such as AIM, Yahoo, ICQ, MSN, and Jabber. Advanced features and additional protocols are available as plugins.";
dict.entries['web']['kvirc'] = "A highly configurable graphical IRC client with an MDI interface, built-in scripting language, support for IRC DCC, drag & drop file browsing, and much more. KVIrc uses the KDE widget set, can be extended using its own scripting language, integrates with KDE, and supports custom plugins.";
dict.entries['web']['linphone'] = "Linphone is an audio and video internet phone using the SIP protocol. It has a GTK+ and console interface, includes a large variety of audio and video codecs, and provides IM features.";
dict.entries['web']['loqui'] = "Loqui is a IRC/chat client based on GTK+, supports multiple servers and multiple protocols, has and the common buffer (a buffer to show messages on the channels that not currently selected).";
dict.entries['web']['lostirc'] = "LostIRC is a simple, yet very useful IRC-client. It has features such as tab-autocompletion, multiple server support, automatic joining of servers/channels and DCC sending which should cover the needs of most people.";
dict.entries['web']['mumble'] = "Mumble is a low-latency, high quality voice chat program for gaming. It features noise suppression, encrypted connections for both voice and instant messaging, automatic gain control and low latency audio with support for multiple audio standards. Mumble includes an in-game overlay compatible with most open-source and commercial 3D applications.";
dict.entries['web']['pidgin'] = "Pidgin is a graphical, modular instant messaging client capable of using multiple networks at once. Currently supported are: AIM/ICQ, Yahoo!, MSN, IRC, Jabber/XMPP/Google Talk, Napster, Zephyr, Gadu-Gadu, Bonjour, Groupwise, Sametime, SIMPLE, MySpaceIM, and MXit.";
dict.entries['web']['pork'] = "Pork is an ncurses-based AOL Instant Messenger and IRC client. It uses the OSCAR protocol (the one the windows client uses) to access AIM. Pork features Perl scripting; an online help system; the ability to configure nearly all aspects of the program's look-and-feel; an alias system; and a powerful, fully-configurable key binding system.";
dict.entries['web']['psi'] = "Psi is a free instant messaging application designed for the Jabber (XMPP) IM network (including Google Talk). It has full Unicode support, and supports many important XMPP features like file transfer, group chat, encryption etc.";
dict.entries['web']['quassel'] = "Quassel is a modern, cross-platform, distributed IRC client, meaning that one or more clients can attach to and detach from the central core. It's much like the popular combination of screen and a text-based IRC client such as WeeChat or irssi, but graphical.";
dict.entries['web']['ring'] = "Ring (ring.cx) is a secure and distributed voice, video and chat communication platform that requires no centralized server and leaves the power of privacy in the hands of the user.";
dict.entries['web']['scrollz'] = "ScrollZ is advanced IRC client based on ircII code. It adds features normally found in ircII scripts like Toolz, PhoEniX, GargOyle or Lice.";
dict.entries['web']['sic'] = "sic is an extremely fast, small and simple irc client. It reads commands from standard input and prints all server output to standard output.";
dict.entries['web']['skype'] = "Skype is a telecommunications application software product that specializes in providing video chat and voice calls between computers, tablets, mobile devices, the Xbox One console, and smartwatches via the Internet and to regular telephones.";
dict.entries['web']['smuxi'] = "Smuxi is an irssi-inspired, flexible, user-friendly and cross-platform IRC client for sophisticated users, targeting the GNOME desktop.";
dict.entries['web']['telegramdesktop'] = "Telegram is a messaging app with a focus on speed and security, it is super-fast, simple and free. You can use Telegram on all your devices at the same time — your messages sync seamlessly across any number of your phones, tablets or computers.";
dict.entries['web']['tinyirc'] = "A very small, stripped down IRC client. It doesn't have most of the more advanced commands in the ircII family of IRC Clients, nor does it have any color, but it works, and it's tiny.";
dict.entries['web']['tkabber'] = "Tkabber is a GUI client for XMPP (Jabber) instant messaging protocol. It provides full support of basic XMPP specifications as well as many protocol extensions (XEPs), such as multi-user conferencing, file transfers, extensive handling of privacy lists and much more.";
dict.entries['web']['tormessenger'] = "TOR Anonymity Network application and an instant messanging client based on Instantbird.";
dict.entries['web']['twinkle'] = "Twinkle is a soft-phone for making telephone calls over an IP network using the SIP protocol. You can use it for direct IP phone to IP phone communication or in a network using a SIP proxy to route your calls.";
dict.entries['web']['weechat'] = "WeeChat (Wee Enhanced Environment for Chat) is a fast and light chat client for many operating systems. Everything can be done with a keyboard. It is customizable and extensible with plugins/scripts";
// web email
dict.entries['web']['alpine'] = "Functional and friendly for novices, text email client. It offers full support of protocols such as IMAP and SMTP as well as security via TLS.";
dict.entries['web']['clawsmail'] = "Fast, light and user friendly e-mail client, based on GTK + 2. The program is extensible with plugins that support additional functions.";
dict.entries['web']['evolution'] = "Evolution is a groupware toolkit that integrates: email program, calendar, address book, to-do list and reminder tools.";
dict.entries['web']['geary'] = "Geary is a lightweight email reader for GNOME designed to let you read your email quickly and effortlessly. Its interface is based on conversations, so you can easily read an entire discussion without having to click from message to message.";
dict.entries['web']['kmail'] = "Full featured graphical email client which supports multiple accounts, mail filtering and email encryption. The program let you configure your workflow and it has good integration into KDE Plasma.";
dict.entries['web']['mutt'] = "Mutt is a sophisticated text-based Mail User Agent which supports MIME, GPG, PGP and threading.";
dict.entries['web']['sylpheed'] = "An e-mail client and news reader based on the GTK + library. Sylpheed supports POP3, IMAP4, SMTP, NNTP and IPv6 protocols, as well as encrypting and signing messages using GnuPG.";
dict.entries['web']['thunderbird'] = "Mail/news client with RSS, chat and integrated spam filter support. It supports different mail accounts, no matter of the used protocol like POP(s) or IMAP(s), has an integrated learning Spam filter, and offers easy organization of mails with tagging and virtual folders.";
dict.entries['web']['trojita'] = "Fast Qt based IMAP e-mail client which respects open standards.";
// web file transfer
dict.entries['web']['aria2'] = "Aria2 is a command line download client with resuming and segmented downloading. Supported protocols are HTTP/HTTPS/ SFTP/FTP/BitTorrent and it also supports Metalink.";
dict.entries['web']['filezilla'] = "FileZilla is a full-featured FTP client with an easy-to-use GUI. It is written in C++ and uses the wxWidgets library.";
dict.entries['web']['gftp'] = "gFTP is a multithreaded FTP client, available in two versions: version for X, written using GLib and GTK+, and version for the console, using only GLib";
dict.entries['web']['jftp'] = "JFtp is a graphical Java network and file transfer client. It supports FTP using its own FTP API and various other protocols like SMB, SFTP, NFS, HTTP, and file I/O using third party APIs.";
dict.entries['web']['kget'] = "KGet is an advanced download manager with support for Metalink and Bittorrent. Downloads are added to the list, where they can be paused, queued, or scheduled for later. This package is part of the KDE networking module.";
dict.entries['web']['lftp'] = "Lftp is a file retrieving tool that supports FTP, HTTP, FISH, SFTP, HTTPS, FTPS and BitTorrent protocols under both IPv4 and IPv6. Lftp has an amazing set of features, while preserving its interface as simple and easy as possible.";
dict.entries['web']['ncftp'] = "NcFTP allows a user to transfer files to and from a remote network site, and offers additional features that are not found in the standard interface, ftp. This version has Readline support enabled.";
dict.entries['web']['uftp'] = "Utility for secure, reliable, and efficient file transfer to multiple receivers simultaneously. This is useful for distributing large files to a large number of receivers, and is especially useful for data distribution over a satellite link where the inherent delay makes any TCP based communication highly inefficient.";
dict.entries['web']['uget'] = "Uget (formerly urlgfe) is a simple, lightweight and easy-to-use download manager written in GTK+.";
dict.entries['web']['wget'] = "Wget is a network utility to retrieve files from the web using HTTP(S) and FTP, the two most widely used internet protocols. It works non-interactively, so it will work in the background, after having logged off.";
dict.entries['web']['youtubedlg'] = "A cross platform front-end GUI of the popular youtube-dl written in wxPython";
// web others
dict.entries['web']['dropbox'] = "A free service that lets you bring your photos, docs, and videos anywhere and share them easily.";
dict.entries['web']['googleearth'] = "Google Earth lets you fly anywhere on Earth to view satellite imagery, maps, terrain, 3D buildings, from galaxies in outer space to the canyons of the ocean.";
dict.entries['web']['megasync'] = "Easy automated syncing between your computers and your MEGA Cloud Drive.";
dict.entries['web']['spideroakone'] = "SpiderOak is an advanced tool designed for storing files in the cloud.";
// web p2p
dict.entries['web']['amule'] = "aMule is a peer-to-peer file sharing application, designed to connect to the eDonkey and Kad networks. It has a wide range of features, including many of the original eMule client";
dict.entries['web']['bitstormlite'] = "This application based on the C++ language integrated with a Gtk+2.0 user-friendly gui has a possibility to download a huge amount of data from any .torrent file taken from trackers around the web.";
dict.entries['web']['bittornadogui'] = "GUI interface to the BitTornado bittorrent client. BitTornado is a bittorrent client built on the original BitTorrent client from BitTorrent Inc. This client offers lots of features, and is one of the original bittorrent clients created.";
dict.entries['web']['ctorrent'] = "This application is written in the C++ language and doesn't require any graphical component, such as an X server. Original ctorrent's upstream has stopped its development and now it's kept updated with new releases/bug fixes by a new developer.";
dict.entries['web']['deluge'] = "Deluge is a full-featured, multi-platform, multi-interface BitTorrent client using libtorrent-rasterbar in it's backend and featuring multiple user-interfaces: GTK+, web and console.";
dict.entries['web']['gtkgnutella'] = "Gtk-Gnutella is a reliable and efficient Gnutella client, supporting the latest Gnutella protocol, bandwidth limitation (both incoming and outgoing) traffic compression, and advanced search filters among other features.";
dict.entries['web']['ktorrent'] = "This package contains KTorrent, a BitTorrent peer-to-peer network client, that is based on the KDE platform. KTorrent supports such basic features as downloading, uploading and seeding files on the BitTorrent network. Some features are available as plugins hence you should make sure you have the ones you need enabled.";
dict.entries['web']['mldonkeygui'] = "The GTK+ interface for mldonkey provides a convenient way of managing all mldonkey operations. It gives details about connected servers, downloaded files, friends and lets one search for files in a pleasing way. ";
dict.entries['web']['nicotine'] = "Nicotine is a client for SoulSeek, a light and efficient file sharing system, written in Python and using the GTK2 toolkit, based on the PySoulSeek project. It features uploading, downloading, searching and chatting, with strict bandwidth control, and tries to look like PySoulSeek.";
dict.entries['web']['qbittorrent'] = "BitTorrent client written in C++ and based on libtorrent-rasterbar with a Qt4 user interface. qBittorrent is a feature rich but lightweight client that is very similar to uTorrent.";
dict.entries['web']['rtorrent'] = "rtorrent is a BitTorrent client based on LibTorrent. It uses ncurses and aims to be a lean, yet powerful BitTorrent client, with features similar to the most complex graphical clients.";
dict.entries['web']['transmission'] = "Transmission is a set of lightweight BitTorrent clients (in GUI, CLI and daemon form). All its incarnations feature a very simple, intuitive interface on top on an efficient, cross-platform back-end.";
dict.entries['web']['vuze'] = "Vuze (previously Azureus) is a BitTorrent client used to transfer files via the BitTorrent protocol. Vuze is written in Java, and uses the Azureus Engine.";
// web rss
dict.entries['web']['akregator'] = "Akregator is a news feed reader. It enables you to follow news sites, blogs and other RSS/Atom-enabled websites without the need to manually check for updates using a web browser. It comes with Konqueror integration for adding news feeds and with an internal browser for easy news reading.";
dict.entries['web']['liferea'] = "Liferea is a feed reader, a news reader, and a podcast client that brings together all of the content from your favorite web subscriptions into a simple interface with an embedded graphical browser that's easy to organize and browse.";
dict.entries['web']['quiterss'] = "QuiteRSS is fast and comfortable to user cross-platform RSS/Atom news feeds reader written on Qt/C++.";
dict.entries['web']['rawdog'] = "Rawdog is a feed aggregator, capable of producing a personal 'river of news' or a public 'planet' page. It supports all common feed formats, including all versions of RSS and Atom. By default, it is run from cron, collects articles from a number of feeds, and generates a static HTML page listing the newest articles in date order.";
dict.entries['web']['rssguard'] = "RSS Guard is simple, light and easy-to-use RSS/ATOM feed aggregator developed using Qt framework which supports online feed synchronization.";
dict.entries['web']['rsstail'] = "Console RSS reader that monitors a feed and outputs new entries. This small, simple application reads an RSS feed and outputs it like the 'tail' command. This tool can be used as a plugin in MultiTail.";
dict.entries['web']['tickr'] = "Tickr is a GTK-based RSS/Atom Reader that displays feeds as a smooth scrolling line on your Desktop, as known from TV stations. Open feed links in your favourite Browser. Graphics are highly customizable.";
// web browsers
dict.entries['web']['brave'] = "Brave est un navigateur internet libre et open-source basé sur le navigateur Chromium et son moteur Blink, annoncé par le co-fondateur du projet Mozilla et créateur du JavaScript, Brendan Eich.";
dict.entries['web']['chromium'] = "Chromium est un navigateur internet open-source, démarré par Google pour fournir le code source du navigateur propriétaire Google Chrome.";
dict.entries['web']['conkeror'] = "Conkeror est un navigateur internet orienté clavier, fortement personnalisable et extensible, basé sur Mozilla XULRunner, principalement écrit en JavaScript, et inspiré par des logiciels d'exception comme Emacs et vi.";
dict.entries['web']['cyberfox'] = "Cyberfox est conçu par 8pecxstudios, reprenant là où Mozilla a laissé tomber. S'efforçant de réaliser un navigateur internet X64 bits rapide, stable et fiable, accessible à tous. Cyberfox est basé sur le code source de Mozilla Firefox.";
dict.entries['web']['dillo'] = "Dillo un navigateur internet minimaliste particulièrement destiné pour les ordinateurs et système lents et âgés.";
dict.entries['web']['dooble'] = "Dooble un navigateur internet libre et open source créé pour améliorer la confidentialité. Dooble utilises Qt pour son interface utilisateur.";
dict.entries['web']['elinks'] = "ELinks is a feature-rich program for browsing the web in text mode. It is like enhanced Lynx and Links.";
dict.entries['web']['epiphany'] = "GNOME Web (précédemment appelé Epiphany de 2003-2012) est un navigateur internet libre et open source créé pour l'environnement GNOME.";
dict.entries['web']['falkon'] = "Lightweight web browser based on libqtwebkit.";
dict.entries['web']['firefoxesr'] = "Le navigateur internet Mozilla Firefox - Extended Support Release (ESR). Firefox ESR est un navigateur internet puissant et extensible avec support des technologies modernes pour applications internet.";
dict.entries['web']['firefoxlatest'] = "La dernière version stable du navigateur internet Mozilla Firefox. est un navigateur internet puissant et extensible avec support des technologies modernes pour applications internet.";
dict.entries['web']['googlechrome'] = "Google Chrome est un navigateur internet gratuiciel développé par Google. Il est en partie basé sur des solutions libres comme WebKit et Mozilla.";
dict.entries['web']['icecat'] = "Son principal avantage est éthique : c'est un logiciel entièrement libre. Alors que le code source de Firefox du projet Mozilla est libre, ils distribuent et recommandent cependant des modules et ajouts non-libres.";
dict.entries['web']['iridium'] = "Iridium is a web browser based on Chromium project. It has been customized to not share your data and thus keeping your privacy intact.";
dict.entries['web']['iron'] = "SRWare Iron est un navigateur internet libre, et une transposition de Chromium par l'Allemand SRWare. Son principal but est d'éliminer les suivis d'utilisation et autres fonctions compromettant la confidentialité inclus dans le navigateur Google Chrome.";
dict.entries['web']['konqueror'] = "Konqueror est le navigateur internet et gestionnaire de fichiers avancé de KDE. Konqueror est un navigateur internet conforme aux normes, supportant HTML 4.01, Java, JavaScript, CSS3, et les ajouts Netscape comme Flash.";
dict.entries['web']['links2'] = "Links is a graphics and text mode WWW browser, similar to Lynx. It displays tables, frames, downloads on background, uses HTTP/1.1 keepalive connections.";
dict.entries['web']['lynx'] = "In continuous development since 1992, Lynx sets the standard for text-mode web clients.";
dict.entries['web']['midori'] = "Midori est un navigateur internet léger. Il utilise l'engin de rendu WebKit et l'interface GTK+ 3";
dict.entries['web']['min'] = "A web browser with smarter search, improved tab management, and built-in ad blocking. Includes full-text history search, instant answers from DuckDuckGo, the ability to split tabs into groups, and more.";
dict.entries['web']['netrik'] = "Netrik is an advanced text mode web browser, similar to w3m or Lynx.";
dict.entries['web']['netsurf'] = "Aussi petit qu'une souris, agile comme un singe et disponible gratuitement. NetSurf est un navigateur internet multi-plateforme pour RISC OS, plateformes UNIX (incluant Linux), Mac OS X, et plus.";
dict.entries['web']['opera'] = "Opera est un navigateur internet pour les systèmes Windows, macOS, et Linux développé par Opera Software. Opera est un logiciel libre, sous licence gratuiciel, mais c'est une application dont les sources sont fermées.";
dict.entries['web']['otter'] = "Otter Browser vise à recréer les meilleurs aspect du classique Opera (12.x) en utilisant Qt5.";
dict.entries['web']['palemoon'] = "Pale Moon est un navigateur internet Open Source, basé sur Goanna, disponible pour Microsoft Windows et Linux (avec d'autres système d'exploitation en cours de développement), focalisé sur l'efficacité et la facilité d'utilisation.";
dict.entries['web']['qute'] = "A web browser for Linux, Windows, and macOS operating systems with vim-style key bindings and a minimal GUI. It is keyboard-driven and is inspired by similar software such as Vimperator and dwb.";
dict.entries['web']['seamonkey'] = "SeaMonkey est une suite internet libre et open-source. C'est la continuation de l'ancienne suite d'application Mozilla, basée sur le même code source.";
dict.entries['web']['torbrowser'] = "Le navigateur TOR est une version de Mozilla Firefox qui a été modifiée par Tor Project pour améliorer la sécurité et la confidentialité.";
dict.entries['web']['vivaldi'] = "Vivaldi est un navigateur internet gratuiciel et multiplateforme développé par Vivaldi Technologies, une compagnie fondée par les co-fondateur et ancien CEO d'Opera Software Jon Stephenson von Tetzchner and Tatsuki Tomita.";
dict.entries['web']['w3m'] = "w3m is a text-based World Wide Web browser with IPv6 support. It features excellent support for tables and frames. It can be used as a standalone file pager, too.";
dict.entries['web']['waterfox'] = "Les navigateurs internet Libres, ouverts et privés visent à donner un choix aux utilisateurs et aident à bâtir un monde meilleur.";
