// English localization file for Graphics
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2019/12/30 by pavroo
dict.entries['graphics'] = {};
// graphics editors
dict.entries['graphics']['blender'] = "Blender is an integrated 3d suite for modelling, animation, rendering, post-production, interactive creation and playback (games). Blender has its own particular user interface, which is implemented entirely in OpenGL and designed with speed in mind.";
dict.entries['graphics']['darktable'] = "Darktable manages your digital negatives in a database and lets you view them through a zoomable lighttable. it also enables you to develop raw images and enhance them. It tries to fill the gap between the many excellent existing free raw converters and image management tools (such as ufraw or f-spot). The user interface is built around efficient caching of image metadata and mipmaps, all stored in a database. the user will always be able to interact, even if the full resolution image is not yet loaded.";
dict.entries['graphics']['fotoxx'] = "Fotoxx is a program for improving digital photos. It allows you to navigate through large image directories using a window of thumbnail images, create HDR (high dynamic range) images by combining bright and dark images to improve details visible in both bright and dark areas, create panoramas by joining overlapped images, adjust brightness and color intensity independently for different underlying brightness levels, reduce fog or haze by removing 'whiteness' and intensifying colors, rotate an image (level a tilted image or turn 90 degrees), remove red-eyes from electronic flash photos, sharpen, resize, or crop images, reduce noise in low-light photos, change color depth, and stretch an image by dragging the mouse.";
dict.entries['graphics']['gimp'] = "GIMP is an advanced picture editor. You can use it to edit, enhance, and retouch photos and scans, create drawings, and make your own images. It has a large collection of professional-level editing tools and filters, similar to the ones you might find in Photoshop. Numerous fine-control settings and features like layers, paths, masks, and scripting give you total control over your images. Many image file formats are supported, including JPEG, Photoshop (.psd), and Paint Shop Pro (.psp) files. It can also be used to scan and print photos.";
dict.entries['graphics']['gnomepaint'] = "Gnome-paint is a program inspired by MS Paint and designed for GNOME (and maybe other) desktop environment. It could be used to manipulate images in a very simple way. With a very friendly user interface, gnome-paint is easy to get started for new users.";
dict.entries['graphics']['hugin'] = "Hugin is a panorama photo stitching program. Essentially, Hugin is a GUI frontend for Panorama Tools. Stitching is accomplished by using several overlapping photos taken from the same location, and using control points to align and transform the photos so that they can be blended together to form a larger image. Hugin allows for the easy creation of control points between two images, optimization of the image transforms, and much more.";
dict.entries['graphics']['imagemagick'] = "ImageMagick is a software suite to create, edit, and compose bitmap images. It can read, convert and write images in a variety of formats (over 100) including DPX, EXR, GIF, JPEG, JPEG-2000, PDF, PhotoCD, PNG, Postscript, SVG, and TIFF. Use ImageMagick to translate, flip, mirror, rotate, scale, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.";
dict.entries['graphics']['inkscape'] = "Inkscape is an illustration editor which has everything needed to create professional-quality computer art. You can use it to make diagrams and illustrations, technical drawings, web graphics, clip art, icons and logos. A collection of hands-on tutorials show you how to combine lines, shapes and text of different types and styles to build up a picture.";
dict.entries['graphics']['k3d'] = "K-3D is free-as-in-freedom 3D modeling and animation software. It combines flexible plugins with a visualization pipeline architecture, making K-3D a versatile and powerful tool for artists.";
dict.entries['graphics']['karbon'] = "Karbon is a vector drawing application with an user interface that is easy to use, highly customizable and extensible. That makes Karbon a great application for users starting to explore the world of vector graphics as well as for artists wanting to create breathtaking vector art.";
dict.entries['graphics']['kolourpaint4'] = "KolourPaint is a simple drawing and image editing application for KDE. It aims to be easy to use, providing a level of functionality targeted towards the average user. It is ideal for common tasks such as drawing simple graphics and touching-up photos.";
dict.entries['graphics']['krita'] = "Krita is a creative application for raster images. Whether you want to create from scratch or work with existing images, Krita is for you. You can work with photos or scanned images, or start with a blank slate. Krita supports most graphics tablets out of the box.";
dict.entries['graphics']['lightzone'] = "LightZone is open-source professional-level digital darkroom software for Windows, Mac OS X, and Linux. Rather than using layers as many other photo editors do, LightZone lets the user build up a stack of tools which can be rearranged, turned off and on, and removed from the stack. It's a non-destructive editor, where any of the tools can be re-adjusted or modified later - even in a different editing session.";
dict.entries['graphics']['opentoonz'] = "Open-source full-featured 2D animation creation software. It is based on the software 'Toonz, which was developed by Digital Video S.p.A. in Italy, customized by Studio Ghibli, and has been used for creating its works for many years. Dwango launches this OpenToonz project, in cooperation with Digital Video and Studio Ghibli.";
dict.entries['graphics']['rawtherapee'] = "RawTherapee is an advanced program for developing raw photos and for processing non-raw photos. It is non-destructive, makes use of OpenMP, supports all the cameras supported by dcraw and carries out its calculations in a high precision 32bit floating point engine. RawTherapee supports JPEG, PNG, and TIFF as output format for processed photos.";
dict.entries['graphics']['synfigstudio'] = "Synfig is a vector based 2D animation package. It is designed to be capable of producing feature-film quality animation. It eliminates the need for tweening, preventing the need to hand-draw each frame.";
dict.entries['graphics']['tuxpaint'] = "Tux Paint is meant to be a simple drawing program for young children. It is not meant as a general-purpose drawing tool. It IS meant to be fun and easy to use. Sound effects and a cartoon character help let the user know what's going on, and keeps them entertained.";
dict.entries['graphics']['xpaint'] = "XPaint is suitable for producing simple graphics. It does offer some advanced features such as image processing functions and gradient fill.";
// graphics others
dict.entries['graphics']['camorama'] = "Camorama is a small utility to view and save images from a webcam or any other Video4Linux device. It can apply a number of image filters and make remote captures.";
dict.entries['graphics']['gtkam'] = "GTKam is a graphical application based on GTK+ that allows you to transfer pictures and movies from a digital camera.";
dict.entries['graphics']['kamera'] = "Digital camera support for KDE applications. This package allows any KDE application to access and manipulate pictures on a digital camera.";
dict.entries['graphics']['qcamera'] = "Simply and small Qt based webcam viewer.";
// graphics screenshots
dict.entries['graphics']['flameshot'] = "Flameshot is a powerful yet simple-to-use screenshot software. Notable features include customizable appearance, in-app screenshot editing, D-Bus interface, experimental GNOME/KDE Wayland support, integration with Imgur and support for both GUI and CLI interface.";
dict.entries['graphics']['gnomescreenshot'] = "Screenshot application for GNOME. This tool takes a picture of the desktop or of a window and saves it into a file.";
dict.entries['graphics']['gscreenshot'] = "Python based GUI for Scrot tool, which lets you make a screenshot of your desktop.";
dict.entries['graphics']['kdespectacle'] = "Screenshot capture utility, replaces KSnapshot. Spectacle captures images of the screen. It can capture the whole screen, a specified region, an individual window, or only part of a window.";
dict.entries['graphics']['screengrab'] = "Crossplatform tool for getting screenshots. Screengrab working in Linux and Windows. The program uses Qt and is independent of any desktop environment.";
dict.entries['graphics']['screenieqt'] = "Screenie a small tool to allow you to compose a fancy and stylish screenshots. It is cross-platform (for Linux, Windows and Mac OS X) and very easy to use. You will have an impressive screenshot in just one minute!";
// graphics viewers
dict.entries['graphics']['digikam'] = "Digital photo management program designed to import, organize, enhance, search and export your digital images to and from your computer. It provides a simple interface which makes importing and organizing digital photographs a 'snap'. digiKam enables you to manage large numbers of digital photographs in albums and to organize these photographs for easy retrieval using tags (keywords), captions, collections, dates, geolocation and searches. It has many features for viewing, organizing, processing and sharing your images. Thus, digiKam is a formidable digital asset management (DAM) software including powerful image editing functions.";
dict.entries['graphics']['eog'] = "EoG or the Eye of GNOME is a simple graphics viewer for the GNOME desktop which uses the gdk-pixbuf library. It can deal with large images, and zoom and scroll with constant memory usage. Its goals are simplicity and standards compliance.";
dict.entries['graphics']['eom'] = "EoM or the Eye of MATE is a simple graphics viewer for the MATE desktop which uses the gdk-pixbuf library. It can deal with large images, and zoom and scroll with constant memory usage. Its goals are simplicity and standards compliance.";
dict.entries['graphics']['ephoto'] = "A comprehensive image viewer written using the core EFL.";
dict.entries['graphics']['feh'] = "Feh is a fast, lightweight image viewer which uses imlib2. It is commandline-driven and supports multiple images through slideshows, thumbnail browsing or multiple windows, and montages or index prints (using TrueType fonts to display file info).";
dict.entries['graphics']['geeqie'] = "Geeqie is a browser for graphics files offering single click viewing of your graphics files. It includes thumbnail view, zoom, filtering features and external editor support.";
dict.entries['graphics']['gpicview'] = "GPicView is a lightweight GTK+ 2.x based image viewer with following features: extremely lightweight and fast with low memory usage, very suitable for default image viewer of desktop system, simple and intuitive interface, etc.";
dict.entries['graphics']['gthumb'] = "gThumb is an advanced image viewer and browser. It has many useful features, such as filesystem browsing, slide show, image catalogs, web album creation, camera import, image CD burning, batch file operations and quick image editing features like transformation and color manipulation.";
dict.entries['graphics']['gwenview'] = "Gwenview is an image viewer, ideal for browsing and displaying a collection of images. It is capable of showing images in a full-screen slideshow view and making simple adjustments, such as rotating or cropping images.";
dict.entries['graphics']['lximageqt'] = "A simple image viewer for LXQt. Additional file formats can be processed if one install qt5-image-formats-plugins.";
dict.entries['graphics']['ristretto'] = "Lightweight picture viewer for the Xfce desktop environment.";
dict.entries['graphics']['shotwell'] = "Shotwell is a digital photo organizer designed for the GNOME desktop environment. It allows you to import photos, pictures, images and videos from disk or camera. Shotwell can organize them in collections and in other various ways. The viewer shows them in full-window or fullscreen mode and presents them as galleries or slideshows. The integrated editor can rotate, flip, crop and tag the photos, adjust the colors und remove red eyes. Export is possible to facebook, Flickr or Youtube to share with others. It is able to manage a lot of image formats such as JPEG, PNG, BMP, TIFF and Raw CR2.";
dict.entries['graphics']['viewnior'] = "This is Viewnior, an image viewer program. Created to be simple, fast and elegant. Its minimalistic interface provides more screenspace for your images.";
dict.entries['graphics']['xnview'] = "XnView is an image organizer and general-purpose file manager used for viewing, converting, organizing and editing raster images, as well as general purpose file management. It comes with built-in hex inspection, batch renaming and screen capture tools. It is licensed as freeware for private, educational and non-profit uses. For other uses, it is licensed as commercial software. ";
