// English localization file for Desktop
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2019/12/28 by pavroo
dict.entries['desktop'] = {};
// desktops
dict.entries['desktop']['awesome'] = "A highly configurable dynamic window manager , next generation framework window manager for X. It is very fast, extensible and licensed under the GNU GPLv2 license. It is primarily targeted at power users, developers and any people dealing with every day computing tasks and who want to have fine-grained control on their graphical environment.";
dict.entries['desktop']['bspwm'] = "bspwm is a tiling window manager that represents windows as the leaves of a full binary tree. bspwm supports multiple monitors and is configured and controlled through messages.";
dict.entries['desktop']['budgie'] = "Budgie-Desktop is a GTK+ based desktop environment which focuses on simplicity and elegance. It provides a traditional desktop metaphor based interface utilising customisable panel based menu driven system. Budgie-Desktop is written from scratch utilising many GNOME based sub-systems such as GNOME-Session and Mutter.";
dict.entries['desktop']['cde'] = "Open source graphics environment for Unix-like operating systems. It was developed by The Open Group, its creation aimed at unifying the programming environment operating on many systems from different manufacturers. CDE is the basic graphic environment of many systems such as: Solaris, HP-UX, Tru64, AIX and OpenVMS.";
dict.entries['desktop']['cinnamon'] = "Cinnamon is a desktop environment which provides advanced innovative features and a traditional user experience. The desktop layout is similar to GNOME 2. The underlying technology is forked from gnome-shell. The emphasis is put on making users feel at home and providing them with an easy to use and comfortable desktop experience.";
dict.entries['desktop']['draco'] = "Lightweight Qt5-based desktop environment forked from Lumina.";
dict.entries['desktop']['enlightenment'] = "Enlightenment is an advanced window manager for X11. Unique features include: a fully animated background, nice drop shadows around windows, backed by an extremely clean and optimized foundation of APIs.";
dict.entries['desktop']['fluxbox'] = "Highly configurable and low resource X11 Window manager which is similar to blackbox, from which it is derived, but has been extended with features such as pwm-style window tabs, configurable key bindings, toolbar, and an iconbar. It also includes some cosmetic fixes over blackbox.";
dict.entries['desktop']['gnomeflashback'] = "GNOME Flashback continues the traditional desktop interface which was used in GNOME 2.x, but using modern GNOME technologies.";
dict.entries['desktop']['gnomeshell'] = "GNOME Shell provides core interface functions like switching windows, launching applications or see your notifications. It takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a delightful and easy to use experience. GNOME Shell is the defining technology of the GNOME 3 user experience.";
dict.entries['desktop']['i3'] = "Improved dynamic tiling window manager. Key features of i3 are good documentation, reasonable defaults (changeable in a simple configuration file) and good multi-monitor support. The user interface is designed for power users and emphasizes keyboard usage. i3 uses XCB for asynchronous communication with X11 and aims to be fast and light-weight.";
dict.entries['desktop']['icewm'] = "IceWm is a Window Manager for X Window System. It is fast and memory-efficient, and it provides many different looks including Windows'95, OS/2 Warp 3,4, Motif. It tries to take the best features of the above systems. Additional features include multiple workspaces, opaque move/resize, task bar, window list, mailbox status, digital clock.";
dict.entries['desktop']['jade'] = "Jade is a Desktop Dashboard that provides minimal desktop environment functionality.";
dict.entries['desktop']['jwm'] = "Low resource Window manager ideal for older PCs. It uses a minimum of external libraries, thus very little memory, includes virtual screens, menubar and root-menu popup. JWM is a window manager for the X11 Window System. JWM is written in C and uses only Xlib and (optionally) the shape extension and libXpm. It can support some MWM, GNOME, and WM Spec hints. The menu configuration files are managed in XML format.";
dict.entries['desktop']['kde'] = "KDE Plasma workspace for desktop and laptop computers. Provides the environment for running and managing applications and integrating interaction of applications. It is designed as generic environment for all kinds of desktop applications, not only applications built on the KDE Platform. It integrates best with applications following the standards used by the KDE Platform.";
dict.entries['desktop']['lumina'] = "A plugin-based desktop environment for Unix and Unix-like operating systems. It is designed specifically as a system interface for TrueOS, and systems derived from Berkeley Software Distribution (BSD) in general, but has been ported to various Linux distributions.";
dict.entries['desktop']['lxde'] = "The Lightweight X11 Desktop Environment (LXDE) is a project aimed to provide a desktop environment which is lightweight and fast.";
dict.entries['desktop']['lxqt'] = "LXQt is an advanced, easy-to-use, and fast desktop environment based on Qt technologies. It has been tailored for users who value simplicity, speed, and an intuitive interface. Unlike most desktop environments, LXQt also works fine with less powerful machines.";
dict.entries['desktop']['manokwari'] = "Desktop shell for GNOME 3 with Gtk+ and HTML5 frontend. Manokwari is used by BlankOn Linux distribution.";
dict.entries['desktop']['mate'] = "The MATE Desktop Environment is the continuation of GNOME 2. It provides an intuitive and attractive desktop environment using traditional metaphors for Linux and other Unix-like operating systems. MATE is under active development to add support for new technologies while preserving a traditional desktop experience.";
dict.entries['desktop']['openbox'] = "Openbox is fully functional as a stand-alone working environment, or can be used as a drop-in replacement for the default window manager in the GNOME or KDE desktop environments. Openbox works with your applications, and makes your desktop easier to manage. This is because the approach to its development was the opposite of what seems to be the general case for window managers. Openbox was written first to comply with standards and to work properly. Only when that was in place did the team turn to the visual interface.";
dict.entries['desktop']['pantheon'] = "Pantheon is the desktop environment originally created for the elementary OS distribution. It is written from scratch in Vala, using GTK3 and Granite. With regards to usability and appearance, the desktop has some similarities with GNOME Shell and macOS.";
dict.entries['desktop']['pekwm'] = "The Pek Window Manager is written by Claes Nästen, the code is based on the aewm++ window manager, but it has evolved enough that it no longer resembles aewm++ at all. It has a much expanded feature-set, including window grouping (similar to ion, pwm, or fluxbox), autoproperties, xinerama, keygrabber that supports keychains, and much more.";
dict.entries['desktop']['trinity'] = "The Trinity Desktop Environment (TDE) is a fork of K Desktop Environment 3.5, organized and led by Timothy Pearson, who had coordinated Kubuntu remixes featuring KDE 3.5, after Kubuntu switched to KDE Plasma 4.";
dict.entries['desktop']['wmaker'] = "Written by Alfredo Kojima almost from scratch, resembles the NeXTStep look very closely, and it is now an official GNU project. Window Maker is not overloaded with features, and it is easier to configure than most other window managers. Its final goal is to produce a window manager that doesn't require editing of configuration files. Window Maker is fast and doesn't require tons of memory to run.";
dict.entries['desktop']['xfce'] = "Xfce jest lekkim środowiskiem graficznym dla uniksopodobnych systemów operacyjnych. Celem deweloperów jest uczynienie go szybkim i lekkim, a jednocześnie przyjemnym wizualnie i prostym w użyciu. Wydajnie zaprojektowane szybko ładuje i uruchamia aplikacje dbając o zasoby systemowe.";
