// Polish localization file for Desktop
// Copyright 2018 Pawel "pavroo" Pijanowski <pavroo@onet.eu>
// Under the GNU GPL v3
// Last update 2019/12/28 by pavroo
dict.entries['desktop'] = {};
// desktops
dict.entries['desktop']['awesome'] = "Wysoce konfigurowalny dynamiczny manager okien nowej generacji dla X. Jest bardzo szybki, rozszerzalny i licencjonowany na licencji GNU GPLv2. Jest skierowany przede wszystkim do zaawansowanych użytkowników, programistów i osób zajmujących się codziennymi zadaniami komputerowymi i chcących mieć precyzyjną kontrolę nad swoim środowiskiem graficznym.";
dict.entries['desktop']['bspwm'] = "bspwm to kafelkowy menedżer okien, który reprezentuje okna jako liście pełnego drzewa binarnego. bspwm obsługuje wiele monitorów i jest konfigurowany i kontrolowany za pomocą komunikatów.";
dict.entries['desktop']['budgie'] = "Budgie-Desktop to środowisko graficzne oparte na GTK+, które koncentruje się na prostocie i elegancji. Zapewnia tradycyjny interfejs pulpitu, wykorzystujący konfigurowalny system oparty na panelach. Budgie-Desktop jest napisany od podstaw z wykorzystaniem wielu podsystemów opartych na GNOME, takich jak GNOME-Session i Mutter.";
dict.entries['desktop']['cde'] = "Otwartoźródłowe środowisko graficzne przeznaczone dla systemów uniksowych. Zostało ono opracowane przez The Open Group, powstanie jego miało na celu ujednolicenie środowiska programistycznego działającego na wielu systemach pochodzących od różnych producentów. CDE jest podstawowym środowiskiem graficznym w wielu systemach takich jak: Solaris, HP-UX, Tru64, AIX i OpenVMS.";
dict.entries['desktop']['cinnamon'] = "Cynamon to środowisko graficzne, które zapewnia zaawansowane innowacyjne funkcje i tradycyjny komfort użytkowania. Układ na pulpicie jest podobny do GNOME 2. Podstawowa technologia jest pochodną GNOME-Shell. Nacisk kładziony jest na to, aby użytkownicy czuli się jak u siebie w domu i otrzymali łatwy w obsłudze i komfortowy interfejs.";
dict.entries['desktop']['draco'] = "Lekkie, bazujące na bibliotekach Qt środowisko graficzne wywądzące się z Lumina Desktop.";
dict.entries['desktop']['enlightenment'] = "Enlightenment to zaawansowany menedżer okien dla X11. Unikalne funkcje obejmują: w pełni animowane tło, ładne cienie wokół okien, wspierane przez wyjątkowo czysty i zoptymalizowany fundament interfejsów API.";
dict.entries['desktop']['fluxbox'] = "Wysoce konfigurowalny, lekki menedżer okien X11 podobny do blackboksa, z którego się wywodzi, ale został rozszerzony o takie funkcje jak zakładki okien w stylu pwm, konfigurowalne przypisania klawiszy, panel i panel z ikonami. Zawiera również kosmetyczne poprawki w porównaniu do blackboksa.";
dict.entries['desktop']['gnomeflashback'] = "GNOME Flashback kontynuuje tradycyjny interfejs pulpitu, który był używany w GNOME 2.x, ale przy użyciu nowoczesnych technologii GNOME.";
dict.entries['desktop']['gnomeshell'] = "GNOME Shell zapewnia podstawowe funkcje interfejsu takie jak: przełączanie okien, uruchamianie aplikacji lub wyświetlanie powiadomień. Wykorzystuje możliwości nowoczesnych kart graficznych i wprowadza innowacyjne koncepcje interfejsu użytkownika, zapewniając przyjemne dla oka wrażenia i łatwość jego obsługi. GNOME Shell jest zdefiniowaną technologią interfejsu użytkownika do środowiska GNOME 3.";
dict.entries['desktop']['i3'] = "Dynamiczny, kafelkowy menedżer okien. Najważniejsze cechy i3 to dobra dokumentacja, rozsądne wartości domyślne (zmienne w prostym pliku konfiguracyjnym) i dobra obsługa wielu monitorów. Interfejs użytkownika został zaprojektowany z myślą o zaawansowanych użytkownikach i podkreśla użycie klawiatury. i3 używa XCB do asynchronicznej komunikacji z X11 i ma być szybki i lekki.";
dict.entries['desktop']['icewm'] = "IceWM jest menadżerem okien dla X Window System. Jest szybki, nie zużywa zbyt dużo pamięci RAM, a daje możliwość używania wielu ciekawych motywów, w tym zbliżone do Windows'95, OS/2 Warp 3,4, Motif. Icewm łączy w sobie najlepsze cechy tychże systemów. Dodatkowe właściwości to: wiele obszarów roboczych, dynamiczne przesuwanie/zmiana rozmiaru okien, pasek zadań, lista okien, status skrzynki pocztowej, cyfrowy zegar.";
dict.entries['desktop']['jade'] = "Jade to pulpit zapewniający minimalną funkcjonalność środowiska graficznego.";
dict.entries['desktop']['jwm'] = "Menedżer okien o małych wymaganiach, idealny dla starszych komputerów. Korzysta z minimum zewnętrznych bibliotek, a więc uzywa bardzo mało pamięci, zawiera wirtualne ekrany, pasek menu i wyskakujące menu główne. JWM jest menedżerem okien dla systemu okien X11. JWM jest napisane w C i używa tylko Xlib i (opcjonalnie) rozszerzenia kształtu i libXpm. Może obsługiwać niektóre wskazówki MWM, GNOME i WM Spec. Pliki konfiguracyjne menu są zarządzane w formacie XML.";
dict.entries['desktop']['kde'] = "Środowisko przestrzeni roboczej KDE Plazma do komputerów stacjonarnych i przenośnych. Pakiet udostępnia środowisko do uruchamiania i zarządzania aplikacjami oraz wzajemnej współpracy między nimi. Zostało ono zaprojektowane jako uniwersalne środowisko do wszelkiego rodzaju aplikacji biurowych, przeznaczonych nie tylko na platformę KDE. Środowisko najlepiej integruje się z aplikacjami zgodnymi ze standardami obsługiwanymi przez KDE.";
dict.entries['desktop']['lumina'] = "Środowisko graficzne dla systemów BSD i GNU/Linux, bazujące na bibliotece Qt. Tworzone głównie z myślą o systemie PC-BSD, jednak jest również dostępne dla wielu dystrybucji Linuxa.";
dict.entries['desktop']['lxde'] = "Lightweight X11 Desktop Environment (LXDE) to projekt mający na celu zapewnienie środowiska graficznego na komputery osobiste, które jest lekkie i szybkie.";
dict.entries['desktop']['lxqt'] = "LXQt to zaawansowane, łatwe w użyciu i szybkie środowisko graficzne oparte na technologiach Qt. Zostało stworzone dla użytkowników ceniących prostotę, szybkość i intuicyjny interfejs. W przeciwieństwie do większości środowisk graficznych, LXQt działa również dobrze na mniej wydajnych maszynach.";
dict.entries['desktop']['manokwari'] = "Manokwari to GNOME 3 desktop shell bazujący na Gtk+ oraz HTML5. Manokwari jest używany przez dystrybucję Linuksa BlankOn.";
dict.entries['desktop']['mate'] = "Środowisko graficzne MATE jest kontynuacją GNOME 2. Zapewnia intuicyjne i atrakcyjne środowisko graficzne z wykorzystaniem tradycyjnych metafor dla systemu Linux i innych uniksopodobnych systemów operacyjnych. MATE jest aktywnie rozwijany, aby dodać obsługę nowych technologii przy zachowaniu tradycyjnego środowiska graficznego.";
dict.entries['desktop']['openbox'] = "Openbox jest w pełni funkcjonalnym i samodzielnym środowiskiem pracy, które może być stosowane zamiast domyślnego menedżera okien, jak GNOME lub KDE. Openbox współpracuje z aplikacjami i sprawia, że pulpit jest łatwiejszy w zarządzaniu. Dzieje się tak, ponieważ podejście do jego rozwoju było odmienne niż w przypadku innych menedżerów okien. Openbox został napisany głównie, aby zachowywać zgodność ze standardami i poprawnie działać. Twórcy Openboksa wracali do kwestii samego interfejsu graficznego tylko wtedy, gdy było to pożądane.";
dict.entries['desktop']['pantheon'] = "Panteon to środowisko graficzne stworzone pierwotnie dla dystrybucji elementary OS. Jest napisany od zera w Vala, używając GTK3 i Granite. Jeśli chodzi o użyteczność i wygląd, pulpit ma pewne podobieństwo do GNOME Shell i macOS.";
dict.entries['desktop']['pekwm'] = "Menedżer okien Pek został napisany przez Claesa Nästena, kod jest oparty na menedżerze okien aewm ++, ale ewoluował na tyle, że nie przypomina już w ogóle aewm ++. Ma znacznie rozszerzony zestaw funkcji, w tym grupowanie okien (podobnie jak ion, pwm lub fluxbox), autoproperty, xinerama, keygrabber, który obsługuje keychains i wiele więcej.";
dict.entries['desktop']['trinity'] = "Trinity Desktop Environment (TDE) to rozwidlenie K Desktop Environment 3.5, zorganizowane i prowadzone przez Timothy Pearson, który koordynował remiksy Kubuntu z KDE 3.5, po tym jak Kubuntu przeszedł na KDE Plasma 4.";
dict.entries['desktop']['wmaker'] = "Napisany przez Alfredo Kojimę niemal od zera, bardzo przypomina wygląd NeXTStep i jest teraz oficjalnym projektem GNU. Window Maker nie jest przeładowany funkcjami i jest łatwiejszy do skonfigurowania niż większość innych menedżerów okien. Ostatecznym celem jest stworzenie menedżera okien, który nie wymaga edycji plików konfiguracyjnych. Window Maker jest szybki i nie wymaga dużej ilości pamięci do uruchomienia.";
dict.entries['desktop']['xfce'] = "Xfce jest lekkim środowiskiem graficznym dla uniksopodnych systemów operacyjnych. Celem aktualizacji jest szybkość i lekkość, a następnie przyjemną wizualnie i prostym w użyciu. Wydajnie substancje szybko ładuje i uruchamia aplikacje dbając o zasoby systemowe.";
